### ISSUE TITLE
Got error when use example conf.

### ISSUE THREAD

**Issue by jiajie999** [InterestingLab/waterdrop#138]
command:

./bin/start-waterdrop.sh --master yarn --deploy-mode cluster --config ./config/application.conf.template

```
18/08/07 11:00:58 WARN SparkContext: Using an existing SparkContext; some configuration may not take effect.
18/08/07 11:00:58 ERROR ApplicationMaster: User class threw exception: java.lang.AbstractMethodError
java.lang.AbstractMethodError
        at org.apache.spark.internal.Logging$class.initializeLogIfNecessary(Logging.scala:99)
        at io.github.interestinglab.waterdrop.Waterdrop$.initializeLogIfNecessary(Waterdrop.scala:19)
        at org.apache.spark.internal.Logging$class.log(Logging.scala:46)
        at io.github.interestinglab.waterdrop.Waterdrop$.log(Waterdrop.scala:19)
        at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54)
        at io.github.interestinglab.waterdrop.Waterdrop$.logInfo(Waterdrop.scala:19)
        at io.github.interestinglab.waterdrop.Waterdrop$.entrypoint(Waterdrop.scala:99)
        at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:45)
        at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:706)
18/08/07 11:00:58 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.AbstractMethodError
        at org.apache.spark.internal.Logging$class.initializeLogIfNecessary(Logging.scala:99)
        at io.github.interestinglab.waterdrop.Waterdrop$.initializeLogIfNecessary(Waterdrop.scala:19)
        at org.apache.spark.internal.Logging$class.log(Logging.scala:46)
        at io.github.interestinglab.waterdrop.Waterdrop$.log(Waterdrop.scala:19)
        at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54)
        at io.github.interestinglab.waterdrop.Waterdrop$.logInfo(Waterdrop.scala:19)
        at io.github.interestinglab.waterdrop.Waterdrop$.entrypoint(Waterdrop.scala:99)
        at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:45)
        at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:706)
)
18/08/07 11:00:58 INFO SparkContext: Invoking stop() from shutdown hook
```

**Comment by garyelephant** [comment]
@jiajie999 感谢使用 ， 请提供你的spark版本，yarn 版本，和系统版本。

**Comment by jiajie999** [comment]
```
spark 2.3.0 Using Scala version 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_171)

yarn version
Hadoop 2.8.3-amzn-0
Subversion git@aws157git.com:/pkg/Aws157BigTop -r 300391394352b074b85b529e870816a72c6f314a
Compiled by ec2-user on 2018-03-21T23:38Z
Compiled with protoc 2.5.0
From source with checksum 9b41a26e3c4fb07cef2c4aea29394145
This command was run using /usr/lib/hadoop/hadoop-common-2.8.3-amzn-0.jar

```

**Comment by garyelephant** [comment]
我用 `spark 2.3.0 Using Scala version 2.11.8` 测试后，未报错，你试试这个命令会报错吗？

```
./bin/start-waterdrop.sh -m local[2] -e client -c config/application.conf.template
```

**Comment by jiajie999** [comment]
local模式没问题，能正确运行
