### ISSUE TITLE
filter sql 解析字段和条件过滤的问题

### ISSUE THREAD

**Issue by liujianrong** [InterestingLab/waterdrop#160]
原始的报文如下，如果是直接使用select * from fas_info，这样子是ok的， 是因为解析成json后，再使用sql filter 的问题么？ 请问怎么解决？
{"api":"com.aa.fc.util.kafka.consumer.OrderInfoConsumer","appName":"bpep-aa-service","costTime":12000,"date":"2018-10-31 10:28:49","dstTraceId":"25172017045160181031102849216004","method":"handler","response":{"actualAmount":"0.01","endTime":1540952926000,"extOrderSeq":"4651311632414","fee":"0","initiationID":"25172017045160181031102849216004","needUpdateTrsSeq":true,"orderNo":"181031001000413397","originAmount":"0.01","reqSeq":"20181031103216","resultCode":"FCA31000000","resultMsg":"成功","stateCode":"000","stateDesc":"成功","sysAppName":"bpep-aa-service","topicName":"SKY_EYE","tradeTime":1540952914000,"transSeq":"181031500001560835"}}
1、配置：多个filter的组合：
filter {
  replace {
    target_field = "raw_message"
    source_field = "raw_message"
    pattern = "bankCardNo"
    replacement = "accountCode"
  },
  json {
    source_field = "raw_message"
  },
  sql {
    sql = "select api, appName from fas_info",
    table_name = "fas_info"
  }
}
2、错误信息如下：
18/10/31 10:38:24 INFO execution.SparkSqlParser: Parsing command: fas_info
18/10/31 10:38:24 INFO execution.SparkSqlParser: Parsing command: select api, appName from fas_info
18/10/31 10:38:24 INFO scheduler.JobScheduler: Finished job streaming job 1540953495000 ms.0 from job set of time 1540953495000 ms
18/10/31 10:38:24 INFO scheduler.JobScheduler: Starting job streaming job 1540953500000 ms.0 from job set of time 1540953500000 ms
18/10/31 10:38:24 ERROR scheduler.JobScheduler: Error running job streaming job 1540953495000 ms.0
org.apache.spark.sql.AnalysisException: cannot resolve '`api`' given input columns: []; line 1 pos 7;
'Project ['api, 'appName]
+- SubqueryAlias fas_info
   +- LogicalRDD

        at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:88)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:85)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:288)
        at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:268)
        at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:268)
        at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:279)
        at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:289)
        at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1$1.apply(QueryPlan.scala:293)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:285)
        at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:293)
        at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$6.apply(QueryPlan.scala:298)
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)

**Comment by garyelephant** [comment]
@liujianrong 明天14:00点前给你问题解决方法。

**Comment by liujianrong** [comment]
> @liujianrong 明天14:00点前给你问题解决方法。

ok,thanks

**Comment by garyelephant** [comment]
@liujianrong 请加微信`garyelephant`
