### ISSUE TITLE
Exception StackTrace: java.lang.ClassNotFoundException: file

### ISSUE THREAD

**Issue by xjzhou** [InterestingLab/waterdrop#192]
用socket例子运行正常，换了个格式，配置文件如下
```
spark {
  # Waterdrop defined streaming batch duration in seconds
  spark.streaming.batchDuration = 5

  spark.app.name = "DJ-Waterdrop"
  spark.ui.port = 13000
}

input {
    file {
        path = "file:///data/xjzhou/devtools/waterdrop/current/data"
        table_name = "accesslog"
        format = "text"
    }
}

filter {
    lowercase {
    }
}

output {
    file {
        path = "file:///data/xjzhou/devtools/waterdrop/current/logs"
        serializer = "text"
    }
} 
```

运行错误提示
```
Fatal Error,

Please contact garygaowork@gmail.com or issue a bug in https://github.com/InterestingLab/waterdrop/issues

Reason: file

Exception StackTrace: java.lang.ClassNotFoundException: file
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
```

**Comment by RickyHuo** [comment]
@xjzhou 麻烦提供Waterdrop版本号

**Comment by xjzhou** [comment]
> @xjzhou 麻烦提供Waterdrop版本号
waterdrop-1.1.0
spark 2.2.0
我换成 waterdrop-1.1.2，spark2.2.4又提示这个错误
```
Fatal Error,

Please contact garygaowork@gmail.com or issue a bug in https://github.com/InterestingLab/waterdrop/issues

Reason: Text data source supports only a single column, and you have 2 columns.;

Exception StackTrace: org.apache.spark.sql.AnalysisException: Text data source supports only a single column, and you have 2 columns.;
        at org.apache.spark.sql.execution.datasources.text.TextFileFormat.verifySchema(TextFileFormat.scala:46)
        at org.apache.spark.sql.execution.datasources.text.TextFileFormat.prepareWrite(TextFileFormat.scala:66)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:142)
```
其实只是个很简单的文件，内容如下
```
:) cat ///data/xjzhou/devtools/waterdrop/current/data/test.1538299223343.log
AAAAAAAAAA
BBBBBBBBBBBB
cccc
aaaaabbbbbbCCCCCC
dddddD
```

**Comment by RickyHuo** [comment]
@xjzhou  因为使用lowercase，导致数据里面多了一列， output serializer 应设为json

```
output {
    file {
        path = "file:///data/xjzhou/devtools/waterdrop/current/logs"
        serializer = "json"
    }
}
```

**Comment by garyelephant** [comment]
@RickyHuo 我们可以考虑，针对这个情况做以下2点改进：

**Comment by garyelephant** [comment]
```
spark {
  # Waterdrop defined streaming batch duration in seconds
  spark.streaming.batchDuration = 5

  spark.app.name = "DJ-Waterdrop"
  spark.ui.port = 13000
}

input {
    file {
        path = "file:///data/xjzhou/devtools/waterdrop/current/data"
        table_name = "accesslog"
        format = "text"
    }
}

filter {
    lowercase {
    }
    remove {
        source_field = ["raw_message"]
    }
}

output {
    file {
        path = "file:///data/xjzhou/devtools/waterdrop/current/logs"
        serializer = "text"
    }
} 
```

**Comment by xjzhou** [comment]
感谢🙏 @garyelephant @RickyHuo 
刚刚试用，我在继续摸索下。

**Comment by garyelephant** [comment]
@xjzhou 棒
