### ISSUE TITLE
filter json报错

### ISSUE THREAD

**Issue by zhang374723384** [InterestingLab/waterdrop#204]
使用json filter有如下报错
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.DataFrameReader.json(Lorg/apache/spark/sql/Dataset;)Lorg/apache/spark/sql/Dataset;
        at io.github.interestinglab.waterdrop.filter.Json.process(Json.scala:60)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$batchProcessing$2.apply(Waterdrop.scala:341)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$batchProcessing$2.apply(Waterdrop.scala:339)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at io.github.interestinglab.waterdrop.Waterdrop$.batchProcessing(Waterdrop.scala:339)
        at io.github.interestinglab.waterdrop.Waterdrop$.process(Waterdrop.scala:182)
        at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:158)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:49)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:49)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:49)
        at scala.util.Try$.apply(Try.scala:192)

源码中直接将DateSet写入spark.read.json并不支持这种语法啊

**Comment by garyelephant** [comment]
请把你的完整配置文件，启动命令和原始数据示例发一下。

**Comment by zhang374723384** [comment]
> 请把你的完整配置文件，启动命令和原始数据示例发一下。

实例数据
{"stage_sum":"3","channel":"weibo","id_card":"1102221919191919","is_unique":"1","real_name":"丁彦雨航"}

配置如下
spark {
  # Waterdrop defined streaming batch duration in seconds
  spark.streaming.batchDuration = 5

  spark.app.name = "Waterdrop"
  spark.executor.instances = 1
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}

input {
  hdfs {
    path = "hdfs://master01.joydata.com:8020/tmp/waterdrop/test.data"
    table_name = "test"
    format = "json"
  }
}

filter {
    json {
         source_field = "channel"
    }
}

output {
    stdout {}
}

启动命令
./bin/start-waterdrop.sh --master yarn --deploy-mode client  --config ./config/test_binlog.conf

**Comment by garyelephant** [comment]
@zhang374723384 收到，我们立即跟进你的问题，请加微信`garyelephant`

**Comment by garyelephant** [comment]
spark2.2 才开始支持spark.read.json(), 我们计划做一下spark2.1 的兼容
