### ISSUE TITLE
还有权限的问题？？：java.lang.NoSuchFieldError: CREATE_NOGRANT

### ISSUE THREAD

**Issue by WilliamShen2019** [InterestingLab/waterdrop#250]
在waterdrop-env.sh 里配置了SPARK_HOME,
./bin/start-waterdrop.sh -m yarn -e client --config ./config/first.conf，报了以下错误：

2019-03-05 11:52:24,570 | WARN  | main | HiveConf of name hive.authorization.msck.enabled does not exist | org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:2753)
2019-03-05 11:52:24,571 | WARN  | main | HiveConf of name hive.metastore.rdb.password.decode.enable does not exist | org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:2753)
2019-03-05 11:52:24,571 | WARN  | main | HiveConf of name hive.metastore.db.ssl.enabled does not exist | org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:2753)
2019-03-05 11:52:28,023 | WARN  | main | HiveConf of name hive.authorization.msck.enabled does not exist | org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:2753)
2019-03-05 11:52:28,024 | WARN  | main | HiveConf of name hive.metastore.rdb.password.decode.enable does not exist | org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:2753)
2019-03-05 11:52:28,024 | WARN  | main | HiveConf of name hive.metastore.db.ssl.enabled does not exist | org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:2753)
Exception in thread "main" java.lang.NoSuchFieldError: CREATE_NOGRANT
        at org.apache.spark.sql.hive.client.HiveClientImpl.org$apache$spark$sql$hive$client$HiveClientImpl$$sqlTypeConventer(HiveClientImpl.scala:637)
        at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$org$apache$spark$sql$hive$client$HiveClientImpl$$convertToHivePrivs$1$$anonfun$apply$13.apply(HiveClientImpl.scala:627)
        at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$org$apache$spark$sql$hive$client$HiveClientImpl$$convertToHivePrivs$1$$anonfun$apply$13.apply(HiveClientImpl.scala:626)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at ......

**Comment by WilliamShen2019** [comment]
为啥还有一堆跟hive相关的东西找不到？

2019-03-05 11:52:24,570 | WARN | main | HiveConf of name hive.authorization.msck.enabled does not exist | org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:2753)
2019-03-05 11:52:24,571 | WARN | main | HiveConf of name hive.metastore.rdb.password.decode.enable does not exist | org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:2753)
2019-03-05 11:52:24,571 | WARN | main | HiveConf of name hive.metastore.db.ssl.enabled does not exist | org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:2753)
2019-03-05 11:52:28,023 | WARN | main | HiveConf of name hive.authorization.msck.enabled does not exist | org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:2753)
2019-03-05 11:52:28,024 | WARN | main | HiveConf of name hive.metastore.rdb.password.decode.enable does not exist | org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:2753)
2019-03-05 11:52:28,024 | WARN | main | HiveConf of name hive.metastore.db.ssl.enabled does not exist | org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:2753)
