### ISSUE TITLE
[Deadline 2019/03/20] 以集群模式运行water，找不到：plugins.tar.gz

### ISSUE THREAD

**Issue by WilliamShen2019** [InterestingLab/waterdrop#251]
--deploy-mode cluster：
./bin/start-waterdrop.sh --master yarn --deploy-mode cluster --config ./config/first.conf
报一下错误
2019-03-05 11:34:59,531 | WARN  | main | Unable to load native-hadoop library for your platform... using builtin-java classes where applicable | org.apache.hadoop.util.NativeCodeLoader.<clinit>(NativeCodeLoader.java:62)
2019-03-05 11:34:59,658 | WARN  | main | Your hostname, localhost.localdomain resolves to a loopback address: 127.0.0.1; using 192.168.1.102 instead (on interface bond4) | org.apache.spark.internal.Logging$class.logWarning(Logging.scala:66)
2019-03-05 11:34:59,658 | WARN  | main | Set SPARK_LOCAL_IP if you need to bind to another address | org.apache.spark.internal.Logging$class.logWarning(Logging.scala:66)
Exception in thread "main" java.io.FileNotFoundException: File file:/data/waterdrop-1.2.1/plugins.tar.gz does not exist
        at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:635)
        at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:861)
        at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:625)
        at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:479)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:346)
......

**Comment by garyelephant** [comment]
你好，使用cluster模式提交前，需要您先执行如下命令：

**Comment by garyelephant** [comment]
你好，从waterdrop v1.2.4 开始，执行start-waterdrop.sh ，它将会自动为你打包，不再需要以上人工操作
