### ISSUE TITLE
按照帮助文档快速开始运行socketStream程序出错

### ISSUE THREAD

**Issue by sunfu103** [InterestingLab/waterdrop#265]
[INFO] Loading config file: ./config/application.conf
ANTLR Runtime version 4.7 used for parser compilation does not match the current runtime version 4.5.3ANTLR Runtime version 4.7 used for parser compilation does not match the current runtime version 4.5.3

===============================================================================

Fatal Error,

Please contact garygaowork@gmail.com or issue a bug in https://github.com/InterestingLab/waterdrop/issues

Reason: bug in method caller: not valid to create ConfigValue from: ConfigString("socketStream")

Exception StackTrace: com.typesafe.config.ConfigException$BugOrBroken: bug in method caller: not valid to create ConfigValue from: ConfigString("socketStream")
	at com.typesafe.config.impl.ConfigImpl.fromAnyRef(ConfigImpl.java:275)
	at com.typesafe.config.impl.ConfigImpl.fromAnyRef(ConfigImpl.java:253)
	at com.typesafe.config.impl.ConfigImpl.fromAnyRef(ConfigImpl.java:269)
	at com.typesafe.config.impl.ConfigImpl.fromAnyRef(ConfigImpl.java:193)
	at com.typesafe.config.ConfigValueFactory.fromAnyRef(ConfigValueFactory.java:66)
	at com.typesafe.config.ConfigValueFactory.fromIterable(ConfigValueFactory.java:108)
	at com.typesafe.config.ConfigValueFactory.fromIterable(ConfigValueFactory.java:145)
	at io.github.interestinglab.waterdrop.config.ConfigVisitorImpl.visitInputBlock(ConfigVisitorImpl.java:114)
	at io.github.interestinglab.waterdrop.config.ConfigVisitorImpl.visitInputBlock(ConfigVisitorImpl.java:22)
	at io.github.interestinglab.waterdrop.configparser.ConfigParser$InputBlockContext.accept(ConfigParser.java:287)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at io.github.interestinglab.waterdrop.config.ConfigVisitorImpl.visitConfig(ConfigVisitorImpl.java:35)
	at io.github.interestinglab.waterdrop.config.ConfigVisitorImpl.visitConfig(ConfigVisitorImpl.java:22)
	at io.github.interestinglab.waterdrop.configparser.ConfigParser$ConfigContext.accept(ConfigParser.java:121)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at io.github.interestinglab.waterdrop.config.ConfigBuilder.load(ConfigBuilder.scala:38)
	at io.github.interestinglab.waterdrop.config.ConfigBuilder.<init>(ConfigBuilder.scala:17)
	at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:96)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:49)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:49)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:49)
	at scala.util.Try$.apply(Try.scala:192)
	at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:49)
	at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

===============================================================================

**Comment by garyelephant** [comment]
你好，请提供
（1）Waterdrop启动命令
（2）Waterdrop配置文件

请加微信garyelephant，为你解决问题

**Comment by garyelephant** [comment]
```
ANTLR Runtime version 4.7 used for parser compilation does not match the current runtime version 4.5.3ANTLR Runtime version 4.7 used for parser compilation does not match the current runtime version 4.5.3
```

你的问题是jar包依赖冲突了，可以下载一下最新版本试试，应该没事了：
https://github.com/InterestingLab/waterdrop/releases/download/v1.2.3/waterdrop-1.2.3.zip
