### ISSUE TITLE
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException: ConfigObject is immutable, you can't call Map.put

### ISSUE THREAD

**Issue by 9553973** [InterestingLab/waterdrop#288]
jdk version 1.8.0_92-b14、spark-2.1.1、waterdrop-1.3.0
streaming.conf.template
./bin/start-waterdrop.sh --master local[2] --deploy-mode client --config ./config/streaming.conf.template

19/03/29 18:53:47 ERROR Utils: Exception encountered
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException: ConfigObject is immutable, you can't call Map.put
Serialization trace:
object (com.typesafe.config.impl.SimpleConfig)
config (io.github.interestinglab.waterdrop.input.sparkstreaming.FakeReceiver)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:711)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:711)
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:396)
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:307)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:793)
        at com.twitter.chill.WrappedArraySerializer.read(WrappedArraySerializer.scala:36)
        at com.twitter.chill.WrappedArraySerializer.read(WrappedArraySerializer.scala:23)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:793)
        at org.apache.spark.serializer.KryoDeserializationStream.readObject(KryoSerializer.scala:244)
        at org.apache.spark.rdd.ParallelCollectionPartition$$anonfun$readObject$1$$anonfun$apply$mcV$sp$2.apply(ParallelCollectionRDD.scala:80)
        at org.apache.spark.rdd.ParallelCollectionPartition$$anonfun$readObject$1$$anonfun$apply$mcV$sp$2.apply(ParallelCollectionRDD.scala:80)
        at org.apache.spark.util.Utils$.deserializeViaNestedStream(Utils.scala:198)
        at org.apache.spark.rdd.ParallelCollectionPartition$$anonfun$readObject$1.apply$mcV$sp(ParallelCollectionRDD.scala:80)
        at org.apache.spark.rdd.ParallelCollectionPartition$$anonfun$readObject$1.apply(ParallelCollectionRDD.scala:70)
        at org.apache.spark.rdd.ParallelCollectionPartition$$anonfun$readObject$1.apply(ParallelCollectionRDD.scala:70)
        at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1269)
        at org.apache.spark.rdd.ParallelCollectionPartition.readObject(ParallelCollectionRDD.scala:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:298)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: ConfigObject is immutable, you can't call Map.put
        at com.typesafe.config.impl.AbstractConfigObject.weAreImmutable(AbstractConfigObject.java:193)
        at com.typesafe.config.impl.AbstractConfigObject.put(AbstractConfigObject.java:204)
        at com.typesafe.config.impl.AbstractConfigObject.put(AbstractConfigObject.java:20)
        at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:162)
        at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:711)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
        ... 39 more

**Comment by garyelephant** [comment]
你好，请尝试用 spark >= 2.2 试试，如果还不行，请加微信`garyelephant`为你解决问题。

**Comment by 9553973** [comment]
thanks! 经测试使用local模式2.1.1版本、2.3.1版本都可以测试通过，可能是我们线上spark-2.1.1 standalone模式集群各个节点环境配置差异造成

**Comment by pdlovedy** [comment]
我也遇见了该问题，TS2.1.3，spark2.4.8，yun'x运行样例就出现了
![image](https://user-images.githubusercontent.com/62368627/226503192-3ac065f8-a95d-4154-982d-c7ca6432a365.png)

**Comment by userkdg** [comment]
joker
