### ISSUE TITLE
使用watermark程序报错：

### ISSUE THREAD

**Issue by zjybeijing** [InterestingLab/waterdrop#305]
**版本信息：**
spark版本：spark-2.4.1-bin-hadoop2.7
waterdrop版本:1.3.1, 1.3.2

**测试信息：**
参考示例文档
https://interestinglab.github.io/waterdrop/#/zh-cn/case_study/5
测试文档与示例文档差不多

**错误信息：**
Fatal Error, 

Please contact garygaowork@gmail.com or issue a bug in https://github.com/InterestingLab/waterdrop/issues

Reason: false (of class java.lang.Boolean)

Exception StackTrace: scala.MatchError: false (of class java.lang.Boolean)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream.prepare(KafkaStream.scala:112)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$1$$anonfun$apply$3.apply(Waterdrop.scala:208)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$1$$anonfun$apply$3.apply(Waterdrop.scala:207)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$1.apply(Waterdrop.scala:207)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$1.apply(Waterdrop.scala:206)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at io.github.interestinglab.waterdrop.Waterdrop$.basePrepare(Waterdrop.scala:206)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming$.structuredStreamingProcessing(WaterdropStructuredStreaming.scala:99)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming$.io$github$interestinglab$waterdrop$WaterdropStructuredStreaming$$entrypoint(WaterdropStructuredStreaming.scala:84)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming$$anonfun$1.apply$mcV$sp(WaterdropStructuredStreaming.scala:35)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming$$anonfun$1.apply(WaterdropStructuredStreaming.scala:35)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming$$anonfun$1.apply(WaterdropStructuredStreaming.scala:35)
	at scala.util.Try$.apply(Try.scala:192)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming$.main(WaterdropStructuredStreaming.scala:35)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming.main(WaterdropStructuredStreaming.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by garyelephant** [comment]
@zjybeijing 你好，感谢反馈，方便的话加个微信`garyelephant`, 帮你进一步排查问题。

**Comment by garyelephant** [comment]
fixed by #308
