### ISSUE TITLE
消费kafka的数据到hdfs，启动失败

### ISSUE THREAD

**Issue by celestewang1026** [InterestingLab/waterdrop#341]
19/07/11 12:18:25 INFO utils.AppInfoParser: Kafka version : 0.9.0-kafka-2.0.2
19/07/11 12:18:25 INFO utils.AppInfoParser: Kafka commitId : unknown
Exception in thread "streaming-start" java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.KafkaConsumer.subscribe(Ljava/util/Collection;)V
	at org.apache.spark.streaming.kafka010.Subscribe.onStart(ConsumerStrategy.scala:85)
	at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.consumer(DirectKafkaInputDStream.scala:73)
	at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.start(DirectKafkaInputDStream.scala:259)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$start$7.apply(DStreamGraph.scala:54)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$start$7.apply(DStreamGraph.scala:54)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
19/07/11 12:18:25 INFO ui.JettyUtils: Adding filter org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to /streaming.
19/07/11 12:18:25 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@59fea5f5{/streaming,null,AVAILABLE,@Spark}
19/07/11 12:18:25 INFO ui.JettyUtils: Adding filter org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to /streaming/json.
19/07/11 12:18:25 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@70f4abc1{/streaming/json,null,AVAILABLE,@Spark}
19/07/11 12:18:25 INFO ui.JettyUtils: Adding filter org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to /streaming/batch.
19/07/11 12:18:25 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@ae3c140{/streaming/batch,null,AVAILABLE,@Spark}
19/07/11 12:18:25 INFO ui.JettyUtils: Adding filter org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to /streaming/batch/json.
19/07/11 12:18:25 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@71b0289b{/streaming/batch/json,null,AVAILABLE,@Spark}
19/07/11 12:18:25 INFO ui.JettyUtils: Adding filter org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to /static/streaming.
19/07/11 12:18:25 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@20027c44{/static/streaming,null,AVAILABLE,@Spark}
19/07/11 12:18:25 INFO streaming.StreamingContext: StreamingContext started

**Comment by RickyHuo** [comment]
能提供一下Kafka的版本吗？  可以加我微信 chodomatte 为你解答

**Comment by RickyHuo** [comment]
Spark CDH中Kafka依赖版本过低导致
