### ISSUE TITLE
使用structured streaming写hdfs报错

### ISSUE THREAD

**Issue by zjybeijing** [InterestingLab/waterdrop#375]
waterdrop版本：1.3.3
spark版本：2.4.1

配置文件：
spark {
  spark.app.name = "Waterdrop"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}

input {
  kafkaStream{
    topics = "test_001"
    consumer.bootstrap.servers = "*"
    consumer.group.id = "waterdrop_group1"
    consumer.rebalance.max.retries = 100
    consumer.failOnDataLoss = false
    schema = "{\"name\":\"string\",\"age\":\"integer\",\"addrs\":\"string\"}"
    
  }
}

filter {
    sql {
      table_name = "test11"
      sql = "select name,age,addrs from test11"
    }

}

output {
#stdout {}
  hdfs {
    path = "hdfs://*:8020/user/hive/warehouse/tmp.db/test_2019"
    serializer = "text"
    save_mode = "append"
  }

}

执行命令：
./bin/start-waterdrop-structured-streaming.sh --master local[4] --deploy-mode client --config  ./config/kafka_to_test.conf

示例数据
{"name":"waterdrop","age":20,"addrs":{"country":"中国","city":"北京"}}

问题： 1. stdout {}打印没问题
2. 写hdfs报错：
Fatal Error, 

Please contact garygaowork@gmail.com or issue a bug in https://github.com/InterestingLab/waterdrop/issues

Reason: hdfs

Exception StackTrace: java.lang.ClassNotFoundException: hdfs
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.github.interestinglab.waterdrop.config.ConfigBuilder$$anonfun$createOutputs$1.apply(ConfigBuilder.scala:167)
	at io.github.interestinglab.waterdrop.config.ConfigBuilder$$anonfun$createOutputs$1.apply(ConfigBuilder.scala:156)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.github.interestinglab.waterdrop.config.ConfigBuilder.createOutputs(ConfigBuilder.scala:156)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming$.io$github$interestinglab$waterdrop$WaterdropStructuredStreaming$$entrypoint(WaterdropStructuredStreaming.scala:82)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming$$anonfun$1.apply$mcV$sp(WaterdropStructuredStreaming.scala:35)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming$$anonfun$1.apply(WaterdropStructuredStreaming.scala:35)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming$$anonfun$1.apply(WaterdropStructuredStreaming.scala:35)
	at scala.util.Try$.apply(Try.scala:192)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming$.main(WaterdropStructuredStreaming.scala:35)
	at io.github.interestinglab.waterdrop.WaterdropStructuredStreaming.main(WaterdropStructuredStreaming.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by RickyHuo** [comment]
@zjybeijing  structrued streaming 暂未实现 hdfs output

**Comment by RickyHuo** [comment]
可以加我微信个 chodomatte1994

**Comment by zjybeijing** [comment]
对于这类数据{"name":"waterdrop","age":20,"addrs":{"country":"中国","city":"北京"}}，对于 addrs值是json的想作为string类型获取， structured streaming是可以定义schema ；对于streaming这种使用json获取的是解析后的值【中国，北京】没有key，在streaming下怎么作为string来获取

**Comment by RickyHuo** [comment]
通过json插件解析之后可以直接获取
