### ISSUE TITLE
waterdrop在Spark2.4.3版本中运行报错

### ISSUE THREAD

**Issue by DoublePei** [InterestingLab/waterdrop#379]
问题如下:同样的配置，在spark2.3版本中运行正常，在2.4.3版本中运行错误，错误详情如下

```
Exception in thread "main" java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "io.github.interestinglab.waterdrop.Waterdrop$.log()Lorg/slf4j/Logger;" the class loader (instance of org/apache/spark/util/ChildFirstURLClassLoader) of the current class, io/github/interestinglab/waterdrop/Waterdrop$, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for interface org/apache/spark/internal/Logging have different Class objects for the type org/slf4j/Logger used in the signature
	at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:873)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:214)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:948)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:957)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

其中waterdrop版本1.4.0
调用的conf文件为：

```
spark {
        spark.app.name = "test"
        spark.sql.catalogImplementation = "hive"
        spark.network.timeout=1000000
        spark.executor.heartbeatInterval=800000
        spark.dynamicAllocation.enabled =false
}

input {
   mysql {
        url = "jdbc:mysql:localhost/test?zeroDateTimeBehavior=convertToNull"
        table = "test"
        user = "test"
        password = "test"
        result_table_name = "access_log"
  }
}

filter {
}
output {
stdout {}
}

**Comment by DoublePei** [comment]
昨天测试了一下，发现在新集群的2.3.2版本中运行也出错。
测试情况如下：
1.将老集群的waterdrop原封不动拷贝到新集群
2.新老集群分别下载2.3.3版本。使用相同的spark配置文件，只是指向不同
3.在新老集群分别启动任务。发现老集群spark2.3.3可以直接启动，新集群上不行。

疑惑点在于为什么waterdrop一致，spark版本一致配置相同，提交时出现jar冲突。
因为急于迁移，麻烦关注一下

**Comment by DoublePei** [comment]
原因找到了：
新集群被更改了配置如下 spark-defaults.conf中被添加：
 spark.driver.userClassPathFirst true
 spark.executor.userClassPathFirst true
但是在waterdrop的spark配置中添加
spark.executor.userClassPathFirst=false
spark.driver.userClassPathFirst=false
不起作用。请检查是否将配置过滤
