### ISSUE TITLE
waterdrop-1.4.1同步hive数据到clickHouse报错

### ISSUE THREAD

**Issue by hongwei366** [InterestingLab/waterdrop#397]
配置文件
`spark {
  spark.app.name = "Waterdrop"
  spark.executor.instances = 3
  spark.executor.cores = 2
  spark.executor.memory = "2g"
}
input {
    hive {
        pre_sql = "select * from traffic.tmp_hongwei_ch"
        table_name = "traffic"
    }
}
filter {
    remove {
        source_field = ["year", "month"]
    }
}
output {
    clickhouse {
        host = "ip:9001"
        database = "test"
        table = "ny_taxi"
        fields = ["date", "datetime", "hostname", "uri", "http_code", "request_time", "data_size", "domain"]
        username = "default"
        password = ""
    }
}`
报错信息为：
`19/10/22 18:25:00 INFO clickhouse.ClickHouseDriver: Driver registered
19/10/22 18:25:00 INFO clickhouse.ClickHouseDriver: Creating connection
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:1025)
	at ru.yandex.clickhouse.util.ClickHouseHttpClientBuilder.buildClient(ClickHouseHttpClientBuilder.java:59)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:71)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:58)
	at ru.yandex.clickhouse.BalancedClickhouseDataSource.getConnection(BalancedClickhouseDataSource.java:189)
	at io.github.interestinglab.waterdrop.output.batch.Clickhouse.checkConfig(Clickhouse.scala:90)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$baseCheckConfig$1$$anonfun$apply$4$$anonfun$2.apply(Waterdrop.scala:268)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$baseCheckConfig$1$$anonfun$apply$4$$anonfun$2.apply(Waterdrop.scala:268)
	at scala.util.Try$.apply(Try.scala:192)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$baseCheckConfig$1$$anonfun$apply$4.apply(Waterdrop.scala:268)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$baseCheckConfig$1$$anonfun$apply$4.apply(Waterdrop.scala:267)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$baseCheckConfig$1.apply(Waterdrop.scala:267)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$baseCheckConfig$1.apply(Waterdrop.scala:266)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at io.github.interestinglab.waterdrop.Waterdrop$.baseCheckConfig(Waterdrop.scala:266)
	at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:114)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:37)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:37)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:37)
	at scala.util.Try$.apply(Try.scala:192)
	at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:37)
	at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/10/22 18:25:00 INFO spark.SparkContext: Invoking stop() from shutdown hook
19/10/22 18:25:00 INFO server.AbstractConnector: Stopped Spark@410e94e{HTTP/1.1,[http/1.1]}{0.0.0.0:4041}
19/10/22 18:25:00 INFO ui.SparkUI: Stopped Spark web UI at http://10.222.18.3:4041
19/10/22 18:25:00 INFO cluster.YarnClientSchedulerBackend: Interrupting monitor thread
19/10/22 18:25:00 INFO cluster.YarnClientSchedulerBackend: Shutting down all executors
19/10/22 18:25:00 INFO cluster.YarnSchedulerBackend$YarnDriverEndpoint: Asking each executor to shut down
19/10/22 18:25:00 INFO cluster.SchedulerExtensionServices: Stopping SchedulerExtensionServices
(serviceOption=None,
 services=List(),
 started=false)
19/10/22 18:25:00 INFO cluster.YarnClientSchedulerBackend: Stopped
19/10/22 18:25:00 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/10/22 18:25:00 INFO memory.MemoryStore: MemoryStore cleared
19/10/22 18:25:00 INFO storage.BlockManager: BlockManager stopped
19/10/22 18:25:00 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
19/10/22 18:25:00 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/10/22 18:25:00 INFO spark.SparkContext: Successfully stopped SparkContext
19/10/22 18:25:00 INFO util.ShutdownHookManager: Shutdown hook called
19/10/22 18:25:00 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-7b1e6e40-54a7-4af0-948a-034cbba9221c
`
集群环境是CDH5.14
提交方式：./bin/start-waterdrop.sh --config config/batch.conf -e client -m yarn

**Comment by RickyHuo** [comment]
@hongwei366  https://github.com/InterestingLab/waterdrop/issues/267#issuecomment-481063042

主要是httpclient版本问题

**Comment by hongwei366** [comment]
@RickyHuo 嗯,有什么好的解决办法吗

**Comment by RickyHuo** [comment]
@hongwei366 看看我上面给的链接。 目前解决方案是替换httpclient

**Comment by zjybeijing** [comment]
端口用的不对吧，clickhouse-jdbc是通过http接口通信的(curl host:8123),与客户端链接不同
