### ISSUE TITLE
无法启动：Caused by: java.lang.ClassCastException: org.codehaus.janino.CompilerFactory cannot be cast to org.codehaus.commons.compiler.ICompilerFactory

### ISSUE THREAD

**Issue by JuZhengZhang** [InterestingLab/waterdrop#460]
Caused by: java.lang.ClassCastException: org.codehaus.janino.CompilerFactory cannot be cast to org.codehaus.commons.compiler.ICompilerFactory
	at org.codehaus.commons.compiler.CompilerFactoryFactory.getCompilerFactory(CompilerFactoryFactory.java:129)
	at org.codehaus.commons.compiler.CompilerFactoryFactory.getDefaultCompilerFactory(CompilerFactoryFactory.java:79)
	at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.compile(JaninoRelMetadataProvider.java:432)
	... 61 more

=====
flink version :1.9.2和1.10.0均试过

**Comment by garyelephant** [comment]
@kid-xiong 帮忙看一下

**Comment by RickyHuo** [comment]
使用 Flink 1.9.0 或者下载 waterdrop-dist-2.0.0-alpha-2.11.8-release.zip

**Comment by RickyHuo** [comment]
使用 Flink 1.9.0 或者下载 waterdrop-dist-2.0.0-alpha-2.11.8-release.zip
