### ISSUE TITLE
struct streaming of Waterdrop Error

### ISSUE THREAD

**Issue by ZhangchengHu0923** [InterestingLab/waterdrop#481]
**Waterdrop Version(Waterdrop版本)**
waterdrop-1.4.3

**Spark Version(Spark 版本)**
spark_2.11-2.2.0-cdh6.0.1

**Java Version(Java版本)**
java version "1.8.0_231"

**Waterdrop Config(Waterdrop配置文件)**
```
spark {
  spark.app.name = "Waterdrop"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}

input {
  kafkaStream {
    consumer.bootstrap.servers = "xxx:9092"
    topics = "TestTopic"
    consumer.group.id = "waterdrop_input_group_id"
    result_table_name = "waterdrop_message"
  }
}

filter {

  sql {
      sql = "select string(value) as raw_message from waterdrop_message"
  }

  json {
    source_field = "raw_message"
    target_field = "jsonMap"
    schema_file = "demo.json"
    result_table_name = "flatten_msg"
  }

  // sql {
  //   sql = "select name, count(name), date_format(window.end, 'MMM-dd HH:mm') as time from flatten_msg group by window('datetime', '1 minutes', '1 seconds'), name"
  // }
  // Watermark {
  //      delay_threshold = "5 minutes"
  //      time_field = "tf"
  //      time_type = "UNIX"
  //      watermark_field = "wm"
  // }

  // sql {
  //    table_name = "res"
  //    sql = "select name, count(name), date_format(dt, 'MM-dd HH:mm:00') as time from res group by dt, name"
  // }
}

output {
  stdout {
    streaming_output_mode = "Append"
    # trigger_mode = "ProcessingTime"
    # interval = "5 seconds"
  }
}
```

**command to start waterdrop**
`./bin/start-waterdrop-structured-streaming.sh --master local[4] --deploy-mode client --config ./config/structuredstreaming.conf.template`

**Error Exception**
`20/05/08 14:48:42 ERROR util.Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.KafkaConsumer.poll(Ljava/time/Duration;)Lorg/apache/kafka/clients/consumer/ConsumerRecords;
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1$$anonfun$apply$1$$anonfun$apply$2.apply(KafkaStream.scala:92)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1$$anonfun$apply$1$$anonfun$apply$2.apply(KafkaStream.scala:89)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1$$anonfun$apply$1.apply(KafkaStream.scala:89)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1$$anonfun$apply$1.apply(KafkaStream.scala:85)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1.apply(KafkaStream.scala:85)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1.apply(KafkaStream.scala:78)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1.onQueryProgress(KafkaStream.scala:78)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.doPostEvent(StreamingQueryListenerBus.scala:123)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.doPostEvent(StreamingQueryListenerBus.scala:38)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:72)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.postToAll(StreamingQueryListenerBus.scala:83)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.onOtherEvent(StreamingQueryListenerBus.scala:99)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:75)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:35)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:35)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:72)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$super$postToAll(AsyncEventQueue.scala:85)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply$mcJ$sp(AsyncEventQueue.scala:85)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:82)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:82)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:82)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1$$anonfun$run$1.apply$mcV$sp(AsyncEventQueue.scala:78)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1283)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1.run(AsyncEventQueue.scala:77)
20/05/08 14:48:42 ERROR util.Utils: throw uncaught fatal error in thread spark-listener-group-shared
java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.KafkaConsumer.poll(Ljava/time/Duration;)Lorg/apache/kafka/clients/consumer/ConsumerRecords;
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1$$anonfun$apply$1$$anonfun$apply$2.apply(KafkaStream.scala:92)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1$$anonfun$apply$1$$anonfun$apply$2.apply(KafkaStream.scala:89)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1$$anonfun$apply$1.apply(KafkaStream.scala:89)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1$$anonfun$apply$1.apply(KafkaStream.scala:85)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1.apply(KafkaStream.scala:85)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1.apply(KafkaStream.scala:78)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1.onQueryProgress(KafkaStream.scala:78)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.doPostEvent(StreamingQueryListenerBus.scala:123)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.doPostEvent(StreamingQueryListenerBus.scala:38)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:72)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.postToAll(StreamingQueryListenerBus.scala:83)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.onOtherEvent(StreamingQueryListenerBus.scala:99)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:75)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:35)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:35)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:72)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$super$postToAll(AsyncEventQueue.scala:85)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply$mcJ$sp(AsyncEventQueue.scala:85)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:82)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:82)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:82)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1$$anonfun$run$1.apply$mcV$sp(AsyncEventQueue.scala:78)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1283)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1.run(AsyncEventQueue.scala:77)
Exception in thread "spark-listener-group-shared" java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.KafkaConsumer.poll(Ljava/time/Duration;)Lorg/apache/kafka/clients/consumer/ConsumerRecords;
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1$$anonfun$apply$1$$anonfun$apply$2.apply(KafkaStream.scala:92)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1$$anonfun$apply$1$$anonfun$apply$2.apply(KafkaStream.scala:89)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1$$anonfun$apply$1.apply(KafkaStream.scala:89)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1$$anonfun$apply$1.apply(KafkaStream.scala:85)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1.apply(KafkaStream.scala:85)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1$$anonfun$onQueryProgress$1.apply(KafkaStream.scala:78)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at io.github.interestinglab.waterdrop.input.structuredstreaming.KafkaStream$$anon$1.onQueryProgress(KafkaStream.scala:78)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.doPostEvent(StreamingQueryListenerBus.scala:123)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.doPostEvent(StreamingQueryListenerBus.scala:38)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:72)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.postToAll(StreamingQueryListenerBus.scala:83)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.onOtherEvent(StreamingQueryListenerBus.scala:99)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:75)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:35)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:35)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:72)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$super$postToAll(AsyncEventQueue.scala:85)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply$mcJ$sp(AsyncEventQueue.scala:85)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:82)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:82)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:82)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1$$anonfun$run$1.apply$mcV$sp(AsyncEventQueue.scala:78)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1283)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1.run(AsyncEventQueue.scala:77)
20/05/08 14:48:42 INFO spark.ContextCleaner: Cleaned accumulator 1
20/05/08 14:48:42 INFO storage.BlockManagerInfo: Removed broadcast_0_piece0 on 192.168.1.36:43619 in memory (size: 5.0 KB, free: 366.3 MB)
20/05/08 14:48:42 INFO spark.ContextCleaner: Cleaned accumulator 0
20/05/08 14:48:42 INFO server.AbstractConnector: Stopped Spark@30c31dd7{HTTP/1.1,[http/1.1]}{0.0.0.0:4041}
20/05/08 14:48:42 INFO ui.SparkUI: Stopped Spark web UI at http://192.168.1.36:4041
20/05/08 14:48:42 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
20/05/08 14:48:42 INFO memory.MemoryStore: MemoryStore cleared
20/05/08 14:48:42 INFO storage.BlockManager: BlockManager stopped
20/05/08 14:48:42 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
20/05/08 14:48:42 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
20/05/08 14:48:42 INFO spark.SparkContext: Successfully stopped SparkContext

`

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by RickyHuo** [comment]
@ZhangchengHu0923 能否使用 Spark 2.4 验证一下，是否有相同报错

**Comment by ZhangchengHu0923** [comment]
好的，我试一下
