### ISSUE TITLE
Object 'ORDER_CNT' not found

### ISSUE THREAD

**Issue by chencore** [InterestingLab/waterdrop#482]
**Waterdrop Version(Waterdrop版本)**
2.0.0
**Flink Version(Flink 版本)**
1.9.2
**Java Version(Java版本)**
1.8

**Waterdrop Config(Waterdrop配置文件)**
```

env {
  # You can set flink configuration here
  execution.parallelism = 1
}

source {
  JdbcSource {
        driver = com.mysql.jdbc.Driver
        url = "jdbc:mysql://192.168.2.173:3306/test"
        username="aaaa"
	password="12345"
        query = "select * from ORDER_CNT"
   }
}

transform {
  Sql {
    sql = "select * from ORDER_CNT"
  }
}

sink {
  ConsoleSink {
  }
```

**Error Exception**

'''
Fatal Error, 

Please contact garygaowork@gmail.com or issue a bug in https://github.com/InterestingLab/waterdrop/issues

Reason: SQL validation failed. From line 1, column 15 to line 1, column 23: Object 'ORDER_CNT' not found

Exception StackTrace: org.apache.flink.table.api.ValidationException: SQL validation failed. From line 1, column 15 to line 1, column 23: Object 'ORDER_CNT' not found
	at org.apache.flink.table.calcite.FlinkPlannerImpl.validate(FlinkPlannerImpl.scala:128)
	at org.apache.flink.table.api.internal.TableEnvImpl.sqlQuery(TableEnvImpl.scala:431)
	at io.github.interestinglab.waterdrop.flink.transform.Sql.processBatch(Sql.java:40)
	at io.github.interestinglab.waterdrop.flink.batch.FlinkBatchExecution.start(FlinkBatchExecution.java:50)
	at io.github.interestinglab.waterdrop.Waterdrop.entrypoint(Waterdrop.java:93)
	at io.github.interestinglab.waterdrop.Waterdrop.run(Waterdrop.java:52)
	at io.github.interestinglab.waterdrop.WaterdropFlink.main(WaterdropFlink.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:604)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:466)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:274)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:746)
	at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:273)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:205)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1008)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1081)
	at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1081)
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 15 to line 1, column 23: Object 'ORDER_CNT' not found
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:824)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:809)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4807)
	at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:172)
	at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:177)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:997)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:957)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3111)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3093)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3365)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:997)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:957)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:216)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:932)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:639)
	at org.apache.flink.table.calcite.FlinkPlannerImpl.validate(FlinkPlannerImpl.scala:124)
	... 20 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Object 'ORDER_CNT' not found
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:572)
	... 39 more

===============================================================================

'''

**Comment by kid-xiong** [comment]
如果需要使用sql插件的话，在JdbcSource插件里增加一个参数，resutl_table_name='xxxxxx'
然后sql插件里sql = "select * from xxxx"

**Comment by RickyHuo** [comment]
```
source {
  JdbcSource {
        driver = com.mysql.jdbc.Driver
        url = "jdbc:mysql://xxx:3306/test"
        username="aaaa"
	password="12345"
        query = "select * from ORDER_CNT"
        result_table_name = "flink_view"
   }
}

transform {
  Sql {
    sql = "select * from flink_view"
  }
}
...
```
