### ISSUE TITLE
从hive拉取数据报错：'org.apache.spark.sql.hive.HiveSessionStateBuilder'

### ISSUE THREAD

**Issue by liang-ctrl** [InterestingLab/waterdrop#493]
**Waterdrop Version(Waterdrop版本)**
1.4.3
A clear version of Waterdrop. 

**Spark Version(Spark 版本)**
2.2.1
A clear version of Spark.

**Java Version(Java版本)**
1.8
A clear version of Java.

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {}
input {
    hive {
        pre_sql = "select prod_url from cbd_stg.stg_prod_push_log_bj where insert_date = '2020-05-12'"
        table_name = "access_log"
    }
}
filter {}
output {}
```

**Error Exception**
Add exception about the problem here.(您可以将程序报错信息粘贴在此处)
Exception in thread "main" java.lang.Exception: java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveSessionStateBuilder':
	at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:42)
	at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveSessionStateBuilder':
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1062)
	at org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:137)
	at org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:136)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:136)
	at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:133)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:632)
	at io.github.interestinglab.waterdrop.input.batch.Hive.getDataset(Hive.scala:27)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$registerInputTempView$1.apply(Waterdrop.scala:294)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$registerInputTempView$1.apply(Waterdrop.scala:292)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.github.interestinglab.waterdrop.Waterdrop$.registerInputTempView(Waterdrop.scala:292)
	at io.github.interestinglab.waterdrop.Waterdrop$.batchProcessing(Waterdrop.scala:197)
	at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:119)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:37)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:37)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:37)
	at scala.util.Try$.apply(Try.scala:192)
	at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:37)
**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）
![image](https://user-images.githubusercontent.com/59360902/81801598-40c39e80-9547-11ea-8031-bb1230a3944b.png)

**Comment by liang-ctrl** [comment]
欢迎各位指点迷津
