### ISSUE TITLE
schema解析错误findAndCreateTableSource failed

### ISSUE THREAD

**Issue by banceclub** [InterestingLab/waterdrop#515]
Waterdrop v2.x For Flink
centos7.5
jdk1.8
Flink1.9.3

配置信息:
===========================================================
```
source {
   KafkaTableStream {
    consumer.bootstrap.servers = "localhost:9092"
    consumer.group.id = "crm_group"
    offset.reset = latest
    topics = topicflink
    result_table_name = mbtest
    format = json
    schema = "{\"Billsalebankinfo\":[{\"ADDITIONAL\":\"\",\"AMOUNT\":0.0100,\"AUTH_CODE\":\"wxbca9be376d129592\",\"CARDNO\":\"omC-VjsGvMGi7EX5shlbIBXlUsV0\",\"CARDTYPE\":\"02\",\"CASHTRACENO\":\"\",\"MERCHANTID\":\"A01339S001WEIg112200603140001\",\"ORGCODE\":\"A01339S001\",\"OWNER_ORGCODE\":\"A01339\",\"SALEBANKID\":656.0,\"SALEID\":2341,\"SALENO\":\"00056070\",\"SYSTRACENO\":\"4200000530202006036422595914\",\"TRANSDATE\":\"20200603\",\"TRANSTIME\":\"143430\",\"TRANSTYPE\":\"01\"}],\"Billsaledetailinfo\":[{\"ADDMONEY\":0.0000,\"BRAND\":\"00000001\",\"CUS_TYPE\":\"1\",\"CUTMONEY\":0.0000,\"DECMONEY\":0.0000,\"DISCOUNTMONEY\":69.9900,\"DISCOUNTRATE\":0.0100,\"DIVDISCOUNTRATE\":0.0100,\"DIVSALESVALUE\":0.0100,\"ISOOS\":0,\"ITEMNO\":1.0,\"MARKETINGMONEY\":0.0000,\"OLDDISCOUNTRATE\":100.0000,\"ORGCODE\":\"A01339S001\",\"OWNER_ORGCODE\":\"A01339\",\"PRESENTFLAG\":\"F\",\"PRICETYPE\":\"02\",\"PRODID\":\"21110109150\",\"QTY\":1,\"REMARK\":\"\",\"REMARKCODE\":\"D007\",\"RETAILPRICE\":70.0000,\"RTLSADTLID\":\"000560701\",\"SALEDETAILID\":3439.0,\"SALEID\":2341,\"SALENO\":\"00056070\",\"SALESMODE\":\"DC\",\"SALESPRICE\":0.0100,\"SALESVALUE\":0.0100,\"SELLERUSERID\":\"A01339U0102\"}],\"Billsaleinfo\":[{\"ACTVOUCHERMONEY\":0.0,\"CARDMONEY\":0.01,\"CASHIERCODE\":\"g112\",\"CASHIERUSERID\":\"A01339U2859\",\"CASHMONEY\":0.0,\"CHANGE\":0.0000,\"CURRENCYCODE\":\"RMB\",\"CUS_TYPE\":\"1\",\"CUTMONEY\":0.0000,\"DISCOUNTMONEY\":69.9900,\"LINKSALENO\":\"\",\"LOCALSQL_TIME\":\"20200603143434\",\"LOCAL_TIME\":\"20200603143513\",\"MEMO\":\"\",\"O2OSALETYPE\":\"\",\"ONLINESALE\":1,\"OOSRefErpType\":\"\",\"ORGCODE\":\"A01339S001\",\"OWNER_ORGCODE\":\"A01339\",\"SALEDATE\":\"2020-05-21T14:34:34\",\"SALEDAY\":20200521,\"SALEID\":2341,\"SALENO\":\"00056070\",\"SALETYPE\":\"RT\",\"TOERPFLAG\":0.0,\"TOTALMONEY\":0.0100,\"TOTALQTY\":1,\"UPLOADTIME\":1591166113933,\"UPLOAD_FROM_IP\":\"10.8.153.95\",\"VERID\":\"JT4.92.22\",\"VOUCHERMONEY\":0.0}],\"Billsalepayinfo\":[{\"ACTPAYVALUE\":0.0100,\"CHANGE\":0.0000,\"ORGCODE\":\"A01339S001\",\"OWNER_ORGCODE\":\"A01339\",\"PAYCODE\":\"WeiPay\",\"PAYVALUE\":0.0100,\"SALEID\":2341,\"SALENO\":\"00056070\",\"SALEPAYID\":5320}],\"Billsalepromotioninfo\":[{\"DISCOUNTMONEY\":69.9900,\"DISCOUNTRATE\":0.0100,\"DISCOUNTTYPE\":\"02\",\"GOODSID\":\"21110109150\",\"GOODSTYPE\":\"02\",\"NUMORMONEY\":\"02\",\"ORGCODE\":\"A01339S001\",\"OWNER_ORGCODE\":\"A01339\",\"PRESENTDESCRIPTION\":\"\",\"PRESENTNUMS\":0.0,\"PROMOSTEP\":69.9900,\"PROMOTHOD\":\"05\",\"PROMOTIONRULEDTLID\":\"\",\"PROMOTIONRULEID\":\"000000002\",\"PROMOTIONRULESTEPID\":\"\",\"RTLSADTLID\":\"000560701\",\"SALEDETAILID\":3439.0,\"SALEID\":2341,\"SALENO\":\"00056070\",\"SALEPROMOTIONID\":2188.0}]}"
  }
}



transform {
	sql {
     sql = "select Billsaleinfo as bill from mbtest"
     result_table_name = "posOrder"
	}
	sql {
     sql = "select bill.SALENO as saleNo,bill.TOTALMONEY as totalAmt,bill.TOTALQTY as totalQty,bill.SALEDATE as saleDate from bill"
     result_table_name = "posOrder"
	}
}

sink {
  ConsoleSink {
   result_table_name = "posOrder"
  }


JdbcSink {
     source_table_name = posOrder
     driver = com.mysql.jdbc.Driver
     url = "jdbc:mysql://localhost:3306/testdb"
     username = root
     password = root123456
     query = "REPLACE into pos_cus_order(saleNo,totalAmt,totalQty,saleDate) values(?,?,?,?)"
     batch_size = 5
   }


```

===============================================================================
报错信息如下:

Fatal Error, 

Please contact garygaowork@gmail.com or issue a bug in https://github.com/InterestingLab/waterdrop/issues

Reason: findAndCreateTableSource failed.

Exception StackTrace: org.apache.flink.table.api.TableException: findAndCreateTableSource failed.
	at org.apache.flink.table.factories.TableFactoryUtil.findAndCreateTableSource(TableFactoryUtil.java:67)
	at org.apache.flink.table.factories.TableFactoryUtil.findAndCreateTableSource(TableFactoryUtil.java:54)
	at org.apache.flink.table.descriptors.ConnectTableDescriptor.registerTableSource(ConnectTableDescriptor.java:69)
	at io.github.interestinglab.waterdrop.flink.source.KafkaTableStream.getData(KafkaTableStream.java:99)
	at io.github.interestinglab.waterdrop.flink.stream.FlinkStreamExecution.start(FlinkStreamExecution.java:39)
	at io.github.interestinglab.waterdrop.Waterdrop.entrypoint(Waterdrop.java:93)
	at io.github.interestinglab.waterdrop.Waterdrop.run(Waterdrop.java:52)
	at io.github.interestinglab.waterdrop.WaterdropFlink.main(WaterdropFlink.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:604)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:466)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:274)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:746)
	at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:273)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:205)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1008)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1081)
	at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1081)
Caused by: org.apache.flink.table.api.ValidationException: Could not find the required schema in property 'schema'.
	at org.apache.flink.table.descriptors.SchemaValidator.validate(SchemaValidator.java:81)
	at org.apache.flink.streaming.connectors.kafka.KafkaTableSourceSinkFactoryBase.getValidatedProperties(KafkaTableSourceSinkFactoryBase.java:251)
	at org.apache.flink.streaming.connectors.kafka.KafkaTableSourceSinkFactoryBase.createStreamTableSource(KafkaTableSourceSinkFactoryBase.java:141)
	at org.apache.flink.table.factories.StreamTableSourceFactory.createTableSource(StreamTableSourceFactory.java:49)
	at org.apache.flink.table.factories.TableFactoryUtil.findAndCreateTableSource(TableFactoryUtil.java:65)
	... 21 more

===============================================================================

The program didn't contain a Flink job. Perhaps you forgot to call execute() on the execution environment.

**Comment by RickyHuo** [comment]
问题可复现，简化版配置:

```
env {
  execution.parallelism = 1
}

source {
  KafkaTableStream {
    consumer.bootstrap.servers = "localhost:9092"
    consumer.group.id = "waterdrop_test"
    topics = "waterdrop_test"
    format = "json"
    schema = "{\"people\": [{\"name\": \"rickyhuo\"}], \"animal\": [{\"age\": 2}]}"
    # schema = "{\"people\": {\"name\": \"rickyhuo\"}}"
    result_table_name = "test_1"
  }
}

transform {
}

sink {
  ConsoleSink {}
}
```
