### ISSUE TITLE
Error when using kudu input plugin

### ISSUE THREAD

**Issue by iwasjoker** [InterestingLab/waterdrop#516]
**Waterdrop Version(Waterdrop版本)**

A clear version of Waterdrop. ： waterdrop-1.5.0

**Flink or Spark Version(Flink 或者 Spark 版本)**

A clear version of Flink or Spark.：Spark-2.2.3

**Java or Scala Version(Java或者Scala版本)**

A clear version of Java or Scala.：Java 1.8

**Waterdrop Config(Waterdrop配置文件)** ：
**waterdrop-env.sh** ：SPARK_HOME=/home/software/spark-2.2.3

Please delete sensitive information(请注意删除敏感信息)
**This is my configuration file:**
```
spark {
  # Waterdrop defined streaming batch duration in seconds
  spark.streaming.batchDuration = 5
  spark.app.name = "Waterdrop"
  spark.ui.port = 13000
}

input {
  kudu{
   kudu_master="First_Kudu_Cluster_Master:7051"
   kudu_table="impala::default.test"
   result_table_name="impala::default.test"
 }
}

filter {
  split {
    fields = ["msg", "name"]
    delimiter = ","
  }
}

output {
  kudu{
   kudu_master="Second_Kudu_Cluster_Master:7051"
   kudu_table="mydb.test"
   mode="insert"
 }
}
```

**Running Command(启动命令)**

 ./bin/start-waterdrop.sh --master local[*] --deploy-mode client --config ./config/application.conf

**Error Exception**
20/06/10 19:06:42 INFO execution.SparkSqlParser: Parsing command: impala::default.test
Exception in thread "main" java.lang.Exception: org.apache.spark.sql.AnalysisException: **Invalid view name: impala::default.test;**
        at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:43)
        at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.spark.sql.AnalysisException: Invalid view name: impala::default.test;

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by iwasjoker** [comment]
The table in kudu is an internal table created by impala

**Comment by garyelephant** [comment]
注意：result_table_name 是你在waterdrop中注册的表名称，不可以使用`::`,`.`，不能指定database名称。建议配置如下：

```
input {
  kudu{
   ...
   result_table_name="my_test_table"
 }
}
```

**Comment by iwasjoker** [comment]
The problem is solved, thanks for answering my question 👍
