### ISSUE TITLE
HIVE to CLICKHOUSE :Exception in thread "main" java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by mazeng305** [InterestingLab/waterdrop#518]
**Waterdrop Version(Waterdrop版本)**
waterdrop-1.1.1.zip
**Flink or Spark Version(Flink 或者 Spark 版本)**
Spark:2.4.3
**Java or Scala Version(Java或者Scala版本)**
1.8
**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {
  spark.app.name = "mazeng_Waterdrop"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}
input {hdfs {
    path = "hdfs:///user/hive/warehouse/dm.db/dm_qm_channel_version_summary_day/dt=20200613"
    result_table_name = "dm_qm_channel_version_summary_day_temp"
    format = "text"
}
}
filter {}
output {
  clickhouse {
         host = "xxx:8123"
        #host = "xxx:8123"
        database = "default"
        table = "dm_qm_channel_version_summary_day_test1"
        fields = ["data_date", "project", "data_type", "channel", "version", "version_code", "new_user_count", "accumulated_user_count", "active_user_count", "update_user_count", "recall_user_count", "uninstall_user_count", "inactive_user_count", "seven_active_user_count", "thirty_active_user_count", "retention_1_count", "retention_1_rate", "active_user_app_duration", "avg_active_user_app_duration", "new_user_app_duration", "avg_new_user_app_duration", "active_user_click_count", "avg_active_user_click_count", "new_user_click_count", "avg_new_user_click_count", "active_user_launch_count", "avg_active_user_launch_count", "new_user_launch_count", "avg_new_user_launch_count", "create_time", "update_time", "dt"]
        username = "root"
        password = "xxxx"
    }
}
```

**Running Command(启动命令)**
./bin/start-waterdrop.sh --config config/batch.conf -e client -m 'yarn-client'

**Error Exception**
20/06/17 14:06:56 INFO [dispatcher-event-loop-7] BlockManagerMasterEndpoint: Registering block manager emr-worker-1.cluster-174129:34811 with 366.3 MB RAM, BlockManagerId(2, emr-worker-1.cluster-174129, 34811, None)
found and registered UDFs count[0], UDAFs count[0]
Exception in thread "main" java.lang.AbstractMethodError
        at org.apache.spark.internal.Logging$class.initializeLogIfNecessary(Logging.scala:99)
        at io.github.interestinglab.waterdrop.apis.Plugin.initializeLogIfNecessary(Plugin.scala:10)
        at org.apache.spark.internal.Logging$class.log(Logging.scala:46)
        at io.github.interestinglab.waterdrop.apis.Plugin.log(Plugin.scala:10)
        at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54)
        at io.github.interestinglab.waterdrop.apis.Plugin.logInfo(Plugin.scala:10)
        at io.github.interestinglab.waterdrop.output.Clickhouse.prepare(Clickhouse.scala:102)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$3.apply(Waterdrop.scala:377)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$3.apply(Waterdrop.scala:376)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at io.github.interestinglab.waterdrop.Waterdrop$.basePrepare(Waterdrop.scala:376)
        at io.github.interestinglab.waterdrop.Waterdrop$.batchProcessing(Waterdrop.scala:302)
        at io.github.interestinglab.waterdrop.Waterdrop$.process(Waterdrop.scala:182)

**Screenshots**
![image](https://user-images.githubusercontent.com/66238914/84861558-e2d52a00-b0a3-11ea-986d-14bfef197a9c.png)

**Comment by RickyHuo** [comment]
Waterdrop 1.1 是基于 Spark 2.2 编译的， 如果要使用 2.4 的 Spark ， 请使用版本 >= 1.4
