### ISSUE TITLE
cluster 模式下启动，json解析异常

### ISSUE THREAD

**Issue by Shuny1206** [InterestingLab/waterdrop#522]
**Waterdrop Version(Waterdrop版本)**

waterdrop-1.4.3 

**Flink or Spark Version(Flink 或者 Spark 版本)**
spark2.4.0

**Java or Scala Version(Java或者Scala版本)**

1.8

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)
spark {
  # Waterdrop defined streaming batch duration in seconds
  spark.streaming.batchDuration = 60
  spark.app.name = ""
  spark.ui.port = 13000
  spark.sql.catalogImplementation = "hive"
  spark.driver.maxResultSize=4g
  spark.serializer= "org.apache.spark.serializer.KryoSerializer"
  spark.driver.memory=1g
  spark.executor.memory=1g
  spark.executor.cores=1
  spark.driver.cores=1
  spark.streaming.kafka.maxRatePerPartition=1000
  spark.streaming.backpressure.enabled=true
}
input{
kafkaStream {
   topics = ""
   consumer.bootstrap.servers = ""
   consumer.group.id = ""
  consumer.auto.offset.reset = earliest
}
}

filter{
    json {
   source_field = "raw_message"
   schema_file = ".json"
}
}

output {
#  stdout {}
clickhouse {
    host = " "
    clickhouse.socket_timeout = 50000
    database = " "
    table = " "
    fields = []
#    username = "username"
##    password = "password"
    bulk_size = 60000
}
}

**Running Command(启动命令)**

start-waterdrop.sh --master yarn --deploy-mode cluster--config ./config/yjjy/.conf

**Error Exception**
Caused by: io.github.interestinglab.waterdrop.config.ConfigRuntimeException: Loading file of plugins/json/files/schemas/oc_order.json failed.
  at io.github.interestinglab.waterdrop.filter.Json.parseCustomJsonSchema(Json.scala:133)
  at io.github.interestinglab.waterdrop.filter.Json.prepare(Json.scala:61)

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）
![image](https://user-images.githubusercontent.com/49746910/85499015-63030e80-b613-11ea-9e72-0865086ad037.png)

**Comment by RickyHuo** [comment]
JSON插件请提供下详细的配置，另外提供客户端schema_file文件放置的位置。

**Comment by Shuny1206** [comment]
{"address":"","approvedCause":"","approvedMan":"","approvedTime":"","apptServiceStatus":"","begAppointment":"","billNo":"","businessType":"","cancelReason":"","carNo":"","cashCouponDiscount":"","channel":"","checkCode":"","city":"","coinBackAmount":"","coinDiscount":"","couponDiscount":"","createDate":"","creator":"","discountAmount":"","discountCompose":"","district":"","endAppointment":"","externalKey":"","fee":"","freightCouponDiscount":"","friendsCoinDiscount":"","hisenseBookDate":"","isEnd":"","isInvoice":"","isSuccess":"","marking":"","mobile":"","name":"","nodeName":"","orderId":"","orderSource":"","orderStatus":"","orderType":"","orderVoucher":"","orgCode":"","orgNo":"","ownCoinDiscount":"","paid":"","payType":"","payWay":"","phone":"","pickupSys":"","pickupType":"","platform":"","platformStockVerifitionTime":"","province":"","receiptMobile":"","receiptName":"","refundAmount":"","refundFlag":"","refuseOrderStatus":"","rejectFlag":"","remark":"","returnFlag":"","sStnArea":"","sStnCode":"","sStnName":"","selfTime":"","sendWay":"","seqNo":"","shippingMethod":"","sort":"","ssTotal":"","status":"","stnArea":"","stnCode":"","stnId":"","stnName":"","stockVerifition":"","stockVerifitionTime":"","street":"","tenantId":"","terminatedTime":"","thirdDiscountAmount":"","totalAmount":"","transDate":"","transId":"","transTime":"","translateBillNo":"","transportState":"","unPaid":"","updateDate":"","updater":"","urgentService":"","urgentTime":"","useScore":"","userId":"","ydTotal":"","zipCode":""}

/home/xxx/test/waterdrop-1.4.3/plugins/json/files/schemas

**Comment by RickyHuo** [comment]
请尝试将目录下的 plugins.tar.gz 删除后重新提交

**Comment by Shuny1206** [comment]
这种方法测试过，删除后启动报的异常一样
