### ISSUE TITLE
Expecting a value but got wrong token: 'tab'

### ISSUE THREAD

**Issue by smilenazy** [InterestingLab/waterdrop#538]
**Waterdrop Version(Waterdrop版本)**
1.5.0
**Flink or Spark Version(Flink 或者 Spark 版本)**
2.4.5
**Java or Scala Version(Java或者Scala版本)**
1.8 java 
**Waterdrop Config(Waterdrop配置文件)**
```
spark {
  spark.app.name = "test"
  spark.executor.instances = 3
  spark.executor.cores = 2
  spark.executor.memory = "2g"
  spark.tispark.pd.addresses = " *********:2379, ********* :2379,*********:2379"
  spark.sql.extensions = "org.apache.spark.sql.TiExtensions"
}

input {
    tidb {
        database = "mkdj"
        pre_sql = "select * from tbl_bet_order where bet_status in (5,6) and tester = 0 and order_type = 1"
        table_name = "tbl_bet_order_tmp"
    }
}


filter {
    sql {
        table_name = "t_device_profit_report_tmp"
        sql = "select a.mem_count, a.bet_count, a.win_count, a.bet_amount, a.win_amount, (a.bet_amount - a.win_amount) as settle_amount , (a.bet_amount - a.win_amount)/a.bet_amount as bet_pae,  current_date() as report_date from ( select 	count(distinct (member_id)) as mem_count, 	count(id) as bet_count, 	sum(case bet_status when 5 then 1 else 0 end) as win_count , 	sum(bet_amount) as bet_amount, 	sum(win_amount) as win_amount  	from  tbl_bet_order_tmp where bet_status = 5  ) as a"
    }
}

output {
    tidb {
        url = "jdbc:mysql://*********:4000/mkdj_rp?useUnicode=true&characterEncoding=utf8"
        table = "t_device_profit_report"
        user = "root"
        password = ""
        save_mode = "append"
    }
}

```
**Running Command(启动命令)**

/data/waterdrop-1.5.0/bin/start-waterdrop.sh --config /data/waterdrop-1.5.0/config/test.conf --deploy-mode client --master 'spark://*********:7077' 

**Error Exception**
Exception in thread "main" io.github.interestinglab.waterdrop.config.ConfigException$Parse: /data/waterdrop-1.5.0/config/test.conf: 22: Expecting a value but got wrong token: 'tab' (JSON does not allow unescaped tab in quoted strings, use a backslash escape) (if you intended 'tab' (JSON does not allow unescaped tab in quoted strings, use a backslash escape) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:207)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:203)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:257)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:481)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:253)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:464)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:253)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:464)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:654)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:20)
        at io.github.interestinglab.waterdrop.config.impl.Parseable.rawParseValue(Parseable.java:264)
        at io.github.interestinglab.waterdrop.config.impl.Parseable.rawParseValue(Parseable.java:252)
        at io.github.interestinglab.waterdrop.config.impl.Parseable.parseValue(Parseable.java:184)
        at io.github.interestinglab.waterdrop.config.impl.Parseable.parseValue(Parseable.java:178)
        at io.github.interestinglab.waterdrop.config.impl.Parseable.parse(Parseable.java:303)
        at io.github.interestinglab.waterdrop.config.ConfigFactory.parseFile(ConfigFactory.java:689)
        at io.github.interestinglab.waterdrop.config.ConfigFactory.parseFile(ConfigFactory.java:703)
        at io.github.interestinglab.waterdrop.config.ExposeSparkConf.main(ExposeSparkConf.java:10)
[INFO] spark conf: [ERROR] config file does not exists or cannot be parsed due to invalid format
Exception in thread "main" io.github.interestinglab.waterdrop.config.ConfigException$Parse: /data/waterdrop-1.5.0/config/test.conf: 22: Expecting a value but got wrong token: 'tab' (JSON does not allow unescaped tab in quoted strings, use a backslash escape) (if you intended 'tab' (JSON does not allow unescaped tab in quoted strings, use a backslash escape) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:207)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:203)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:257)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:481)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:253)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:464)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:253)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:464)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:654)
        at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:20)
        at io.github.interestinglab.waterdrop.config.impl.Parseable.rawParseValue(Parseable.java:264)
        at io.github.interestinglab.waterdrop.config.impl.Parseable.rawParseValue(Parseable.java:252)
        at io.github.interestinglab.waterdrop.config.impl.Parseable.parseValue(Parseable.java:184)
        at io.github.interestinglab.waterdrop.config.impl.Parseable.parseValue(Parseable.java:178)
        at io.github.interestinglab.waterdrop.config.impl.Parseable.parse(Parseable.java:303)
        at io.github.interestinglab.waterdrop.config.ConfigFactory.parseFile(ConfigFactory.java:689)
        at io.github.interestinglab.waterdrop.config.ConfigFactory.parseFile(ConfigFactory.java:703)
        at io.github.interestinglab.waterdrop.config.ExposeSparkDriverConf.main(ExposeSparkDriverConf.java:32)

**Comment by RickyHuo** [comment]
可以删除配置文件里的 Tab 键 或者使用""xxx""""包含对应的配置内容
