### ISSUE TITLE
org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID

### ISSUE THREAD

**Issue by bigdatas** [InterestingLab/waterdrop#551]
**Waterdrop Version(Waterdrop版本)**

waterdrop-1.5.0

**Flink or Spark Version(Flink 或者 Spark 版本)**
spark版本2.4.5

**Java or Scala Version(Java或者Scala版本)**

java版本1.8.0_181

**Waterdrop Config(Waterdrop配置文件)**
```
spark {
  spark.app.name = "Waterdrop"
  spark.executor.instances = 4
  spark.executor.cores = 8
  spark.executor.memory = "24g"
}
input {

mysql {
    url = "jdbc:mysql://xx.xx.xx.xx:xxxx/center_account"
    table = "xxxx"
    result_table_name = "center_account_flow"
    user = "xxxx"
    password = "xxxx"
}

}


filter {
}

output {
hdfs {
  path = "hdfs:///user/hive/warehouse/stage.db/merge_s02_center_account_flow/dt=${now}"
    format = "orc"
    save_mode = "append"
    path_time_format = "yyyy-MM-dd"
}
}
```

**Running Command(启动命令)**

/Data/servers/waterdrop-1.5.0/bin/start-waterdrop.sh --config /Data/servers/waterdrop-1.5.0/config/merge_s02_center_account_flow.conf -e client -m 'local[4]'

**Error Exception**
20/07/20 17:20:56 INFO Utils: Successfully started service 'SparkUI' on port 4040.
20/07/20 17:20:56 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://master.hadoop.com:4040
20/07/20 17:20:56 INFO SparkContext: Added JAR file:/Data/servers/waterdrop-1.5.0/lib/Waterdrop-1.5.0-2.11.8.jar at spark://master.hadoop.com:28977/jars/Waterdrop-1.5.0-2.11.8.jar with timestamp 1595236856301
20/07/20 17:20:56 INFO Executor: Starting executor ID driver on host localhost
20/07/20 17:20:56 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' onport 35691.
20/07/20 17:20:56 INFO NettyBlockTransferService: Server created on master.hadoop.com:35691
20/07/20 17:20:56 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
20/07/20 17:20:56 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, master.hadoop.com, 35691, None)
20/07/20 17:20:56 INFO BlockManagerMasterEndpoint: Registering block manager master.hadoop.com:35691 with 366.3 MB RAM, BlockManagerId(driver, master.hadoop.com, 35691, None)
20/07/20 17:20:56 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, master.hadoop.com, 35691, None)
20/07/20 17:20:56 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, master.hadoop.com, 35691, None)
find and register UDFs & UDAFs
20/07/20 17:20:58 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/Data/servers/waterdrop-1.5.0/config/spark-warehouse').
20/07/20 17:20:58 INFO SharedState: Warehouse path is 'file:/Data/servers/waterdrop-1.5.0/config/spark-warehouse'.
20/07/20 17:20:58 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
found and registered UDFs count[2], UDAFs count[0]
20/07/20 17:20:58 INFO Version: Elasticsearch Hadoop v7.6.2 [8aeabb5ee9]
20/07/20 17:20:58 INFO ClickHouseDriver: Driver registered
ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.5.3ANTLR Runtime version 4.7 used for parser compilation does not match the current runtime version 4.5.3Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:84)
	at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parseTableIdentifier(ParseDriver.scala:49)
	at org.apache.spark.sql.Dataset.createTempViewCommand(Dataset.scala:3147)
	at org.apache.spark.sql.Dataset.createOrReplaceTempView(Dataset.scala:3102)
	at io.github.interestinglab.waterdrop.Waterdrop$.registerTempView(Waterdrop.scala:368)
	at io.github.interestinglab.waterdrop.Waterdrop$.registerInputTempView(Waterdrop.scala:311)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$registerInputTempView$1.apply(Waterdrop.scala:295)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$registerInputTempView$1.apply(Waterdrop.scala:292)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at io.github.interestinglab.waterdrop.Waterdrop$.registerInputTempView(Waterdrop.scala:292)
	at io.github.interestinglab.waterdrop.Waterdrop$.batchProcessing(Waterdrop.scala:197)
	at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:119)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:37)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:37)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:37)
	at scala.util.Try$.apply(Try.scala:192)
	at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:37)
	at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:153)
	at org.apache.spark.sql.catalyst.parser.SqlBaseLexer.<clinit>(SqlBaseLexer.java:1175)
	... 31 more
Caused by: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).
	... 33 more
20/07/20 17:21:00 INFO SparkContext: Invoking stop() from shutdown hook
20/07/20 17:21:00 INFO SparkUI: Stopped Spark web UI at http://master.hadoop.com:4040
20/07/20 17:21:00 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
20/07/20 17:21:00 INFO MemoryStore: MemoryStore cleared
20/07/20 17:21:00 INFO BlockManager: BlockManager stopped
20/07/20 17:21:00 INFO BlockManagerMaster: BlockManagerMaster stopped
20/07/20 17:21:00 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
20/07/20 17:21:00 INFO SparkContext: Successfully stopped SparkContext
20/07/20 17:21:00 INFO ShutdownHookManager: Shutdown hook called
20/07/20 17:21:00 INFO ShutdownHookManager: Deleting directory /tmp/spark-26684bec-d9ec-438e-9061-515ad7bfc830
20/07/20 17:21:00 INFO ShutdownHookManager: Deleting directory /tmp/spark-a28a62f2-254d-4e92-aa40-db39998b4afb

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by RickyHuo** [comment]
使用的是原生Spark吗

**Comment by bigdatas** [comment]
是的，原生spark，从spark官网下载的spark-2.4.5-hadoop2.7.0

**Comment by syobject** [comment]
I met the same problem as yours. How did you solve it

**Comment by RayTsui** [comment]
yes, I have the same issue as yours @bigdatas , have you resolved it yet, thanks.
