### ISSUE TITLE
hadoop-3.0-hdfs-web-HftpFileSystem Error

### ISSUE THREAD

**Issue by 1241407808** [InterestingLab/waterdrop#558]
**Waterdrop Version(Waterdrop版本)**

waterdrop-dist-2.0.0-alpha-2.11.8-release

** Hadoop 版本 **  

3.0.0-cdh6.0.1

**Flink or Spark Version(Flink 或者 Spark 版本)**

spark 2.11-2.2.0-cdh6.0.1

**Java or Scala Version(Java或者Scala版本)**

scala 2.11
java 1.8

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {
  spark.app.name = "Waterdrop"
  spark.executor.instances = 4
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}
input {
  hive {
          pre_sql = "SELECT * FROM  ods_buryingpoint.burying_point_log_df WHERE ds='20200723' limit 100;"
          table_name = "burying_point_log_df"
      }
}
filter {
  remove {
        source_field = ["ds"]
    }
}
output {
  Console {}
}
```

**Running Command(启动命令)**

./bin/start-waterdrop-spark.sh --config config/spark.batch.conf -e client -m 'local[4]'

**Error Exception**
Exception in thread "main" java.lang.IllegalAccessError: class org.apache.hadoop.hdfs.web.HftpFileSystem cannot access its superinterface org.apache.hadoop.hdfs.web.TokenAspect$TokenManagementDelegator
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.apache.hadoop.fs.FileSystem.loadFileSystems(FileSystem.java:3202)
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3247)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3286)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:123)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3337)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3305)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:476)
        at org.apache.spark.util.Utils$.getHadoopFileSystem(Utils.scala:1857)
        at org.apache.spark.scheduler.EventLoggingListener.<init>(EventLoggingListener.scala:68)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:532)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2490)
        at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:918)
        at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:910)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:910)
        at io.github.interestinglab.waterdrop.spark.SparkEnvironment.prepare(SparkEnvironment.scala:30)
        at io.github.interestinglab.waterdrop.spark.SparkEnvironment.prepare(SparkEnvironment.scala:14)
        at io.github.interestinglab.waterdrop.config.ConfigBuilder.createEnv(ConfigBuilder.java:185)
        at io.github.interestinglab.waterdrop.config.ConfigBuilder.<init>(ConfigBuilder.java:47)
        at io.github.interestinglab.waterdrop.Waterdrop.entrypoint(Waterdrop.java:84)
        at io.github.interestinglab.waterdrop.Waterdrop.run(Waterdrop.java:52)
        at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by garyelephant** [comment]
你好，waterdrop-v2.x 暂时还不支持hadoop 3.0，后续会考虑支持。

**Comment by yyu123** [comment]
waterdrop-1.5.1-with-spark
hadoop-3.0.0-cdh6.0.0
spark-2.2

INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@4482469c{/metrics/json,null,AVAILABLE,@Spark}
Exception in thread "main" java.lang.IllegalAccessError: class org.apache.hadoop.hdfs.web.HftpFileSystem cannot access its superinterface org.apache.hadoop.hdfs.web.TokenAspect$TokenManagementDelegator
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.apache.hadoop.fs.FileSystem.loadFileSystems(FileSystem.java:3202)
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3247)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3286)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:123)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3337)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3305)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:476)
        at org.apache.spark.util.Utils$.getHadoopFileSystem(Utils.scala:1857)
        at org.apache.spark.scheduler.EventLoggingListener.<init>(EventLoggingListener.scala:68)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:532)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2490)
        at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:918)
        at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:910)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:910)
        at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:105)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:38)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:38)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:38)
        at scala.util.Try$.apply(Try.scala:192)
        at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:38)
        at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/09/22 13:55:40 INFO storage.DiskBlockManager: Shutdown hook called

**Comment by yyu123** [comment]
waterdrop-1.5.1-with-spark  也不支持 hadoop 3.0吗？ 预计什么时候会支持

**Comment by RickyHuo** [comment]
waterdrop-1.5.1 支持 waterdrop-1.5.1-with-spark不支持

**Comment by 1241407808** [comment]
加油，老铁们
