### ISSUE TITLE
waterdrop1.5.1 读取hive数据计算写入hdfs/stdout

### ISSUE THREAD

**Issue by reallyloving** [InterestingLab/waterdrop#559]
**Waterdrop Version(Waterdrop版本)**
1.5.1

**Flink or Spark Version(Flink 或者 Spark 版本)**
spark2.3.1
**Java or Scala Version(Java或者Scala版本)**
1.8.1
**Waterdrop Config(Waterdrop配置文件)**
SPARK_HOME=${SPARK_HOME:-/usr/bin/hadoop/software/spark-2.3.1.v1}

Please delete sensitive information(请注意删除敏感信息)

```
spark {
  spark.app.name = "Waterdrop"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  // 这个配置必需填写
  spark.sql.catalogImplementation = "hive"
  spark.ui.port= 13000
}
input {
    hive {
        pre_sql = "select count(1) from tt.test where partition_time = 18440"
        table_name = "access_log"
    }
}

filter {
}

output {
  stdout {}
}
```

**Running Command(启动命令)**

./bin/start-waterdrop.sh --master yarn --deploy-mode client --config ./config/batch.conf

**Error Exception**
20/08/12 15:00:38 WARN SparkConf: Detected deprecated memory fraction settings: [spark.storage.memoryFraction]. As of Spark 1.6, execution and storage memory management are unified. All memory fractions used in the old model are now deprecated and no longer read. If you wish to use the old memory management, you may explicitly enable `spark.memory.useLegacyMode` (not recommended).
Exception in thread "main" java.lang.NoSuchMethodError: org.elasticsearch.hadoop.cfg.Settings.getSecurityAuthenticationMethod()Lorg/elasticsearch/hadoop/security/AuthenticationMethod;
	at org.elasticsearch.spark.deploy.yarn.security.EsServiceCredentialProvider.credentialsRequired(EsServiceCredentialProvider.scala:104)
	at org.elasticsearch.spark.deploy.yarn.security.EsServiceCredentialProvider.credentialsRequired(EsServiceCredentialProvider.scala:84)
	at org.apache.spark.deploy.yarn.security.YARNHadoopDelegationTokenManager$$anonfun$obtainDelegationTokens$2.apply(YARNHadoopDelegationTokenManager.scala:59)
	at org.apache.spark.deploy.yarn.security.YARNHadoopDelegationTokenManager$$anonfun$obtainDelegationTokens$2.apply(YARNHadoopDelegationTokenManager.scala:58)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.apache.spark.deploy.yarn.security.YARNHadoopDelegationTokenManager.obtainDelegationTokens(YARNHadoopDelegationTokenManager.scala:58)
	at org.apache.spark.deploy.yarn.Client.prepareLocalResources(Client.scala:388)
	at org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:869)
	at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:169)
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:57)
	at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:164)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:500)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2493)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:930)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:921)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:921)
	at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:105)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:38)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:38)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:38)
	at scala.util.Try$.apply(Try.scala:192)
	at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:38)
	at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:880)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Screenshots**
![image](https://user-images.githubusercontent.com/35362731/89990257-ab09ed80-dcb4-11ea-9ce3-953d5da820d6.png)

**Comment by garyelephant** [comment]
是YARN集群开启了kerberos吗

**Comment by reallyloving** [comment]
> 是YARN集群开启了kerberos吗

YARN集群没有开启kerberors认证呢

**Comment by cnmac** [comment]
考虑包冲突问题
