### ISSUE TITLE
java.lang.NoSuchMethodError: net.jpountz.lz4.LZ4BlockInputStream包冲突

### ISSUE THREAD

**Issue by etcxy** [InterestingLab/waterdrop#582]
在电脑本地运行，但一直报包lz4包找不到。网上尝试解决办法，一直没没搞定。
sbt工具不熟，官方的`build.sbt`里，已经exlude这个包了，但还是无法解决。
还望指导，谢谢
**Waterdrop Version(Waterdrop版本)**

waterdrop 1.5.1

**Flink or Spark Version(Flink 或者 Spark 版本)**

spark 2.4.7

**Java or Scala Version(Java或者Scala版本)**
java 1.8 
scala 2.11.8

**Waterdrop Config(Waterdrop配置文件)**

```
######
###### This config file is a demonstration of streaming processing in waterdrop config
######

spark {
  spark.app.name = "Waterdrop"
  spark.executor.instances = 2
  spark.executor.cores = 4
  spark.executor.memory = "1g"
  spark.master="local[8]"
  spark.streaming.batchDuration=1
}

input {
  # This is a example input plugin **only for test and demonstrate the feature input plugin**
  fakestream {
    content = ["Hello World, InterestingLab"]
    rate = 1
  }
}

filter {
  split {
    fields = ["msg", "name"]
    delimiter = ","
    result_table_name = "accesslog"
  }
}

output {
  stdout {
  }
}
```

**Running Command(启动命令)**

```
--master local[4] --deploy-mode client --config ./config/streaming.conf
```

**Error Exception**
```
Exception in thread "streaming-job-executor-1" java.lang.NoSuchMethodError: net.jpountz.lz4.LZ4BlockInputStream.<init>(Ljava/io/InputStream;Z)V
	at org.apache.spark.io.LZ4CompressionCodec.compressedInputStream(CompressionCodec.scala:122)
	at org.apache.spark.sql.execution.SparkPlan.org$apache$spark$sql$execution$SparkPlan$$decodeUnsafeRows(SparkPlan.scala:276)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeTake$1.apply(SparkPlan.scala:368)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeTake$1.apply(SparkPlan.scala:368)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:368)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3389)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2550)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2550)
	at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3370)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withAction(Dataset.scala:3369)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2550)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2764)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$streamingProcessing$1$$anonfun$apply$1.apply(Waterdrop.scala:180)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$streamingProcessing$1$$anonfun$apply$1.apply(Waterdrop.scala:179)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$streamingProcessing$1.apply(Waterdrop.scala:179)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$streamingProcessing$1.apply(Waterdrop.scala:169)
	at io.github.interestinglab.waterdrop.apis.BaseStreamingInput$$anonfun$start$1.apply(BaseStreamingInput.scala:25)
	at io.github.interestinglab.waterdrop.apis.BaseStreamingInput$$anonfun$start$1.apply(BaseStreamingInput.scala:23)
```

**Comment by RickyHuo** [comment]
可以尝试本地重新编译一次后在运行一下

**Comment by etcxy** [comment]
重新编译过，还是无法运行。
在一番折腾后，在`"ru.yandex.clickhouse" % "clickhouse-jdbc" % "0.2.4"`下，发现含有`net.jpountz.lz4`的`1.3.0`版本，exclude之后，异常解决。

具体解决方式:
`waterdrop-core`下的`build.sbt`文件

```
  "ru.yandex.clickhouse" % "clickhouse-jdbc" % "0.2.4"
    excludeAll(ExclusionRule(organization="com.fasterxml.jackson.core"))
    exclude("net.jpountz.lz4", "lz4"),
```
