### ISSUE TITLE
waterdrop1.5.1 hive批量至ck出错

### ISSUE THREAD

**Issue by cloudcba** [InterestingLab/waterdrop#583]
spark {
    spark.app.name = "Waterdrop"
    spark.executor.instances = 2
    spark.executor.cores = 1
    spark.executor.memory = "1g"
}
input {
    hive {
        pre_sql = "select id as id,name as name from cloud_db.hive_test2 limit 10"
        table_name = "v_hive_test2"
    }
}
filter {
    remove {
        source_field = [""]
    }
}
output {
    clickhouse {
        host = "192.168.8.125:8123"
        database = "cloud_db"
        table = "cktest001"
        fields = ["id","name"]
        username = "default"
        password = "test"
    }
}

报错信息如下：
Exception in thread "main" io.github.interestinglab.waterdrop.config.ConfigException$Parse: /home/zuoye_waterdrop/export/conf/clickhouse_tmp_cloud_hivetest.json: 1: Token not allowed in valid JSON: 'spark'
	at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:207)
	at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:203)
	at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.nextToken(ConfigDocumentParser.java:60)
	at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.nextTokenCollectingWhitespace(ConfigDocumentParser.java:71)
	at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:635)
	at io.github.interestinglab.waterdrop.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:20)
	at io.github.interestinglab.waterdrop.config.impl.Parseable.rawParseValue(Parseable.java:264)
	at io.github.interestinglab.waterdrop.config.impl.Parseable.rawParseValue(Parseable.java:252)
	at io.github.interestinglab.waterdrop.config.impl.Parseable.parseValue(Parseable.java:184)
	at io.github.interestinglab.waterdrop.config.impl.Parseable.parseValue(Parseable.java:178)
	at io.github.interestinglab.waterdrop.config.impl.Parseable.parse(Parseable.java:303)
	at io.github.interestinglab.waterdrop.config.ConfigFactory.parseFile(ConfigFactory.java:689)
	at io.github.interestinglab.waterdrop.config.ConfigFactory.parseFile(ConfigFactory.java:703)
	at io.github.interestinglab.waterdrop.config.ExposeSparkConf.main(ExposeSparkConf.java:10)

**Comment by garyelephant** [comment]
@cloudcba 配置文件的格式不是json，文件名请勿用.json，/home/zuoye_waterdrop/export/conf/clickhouse_tmp_cloud_hivetest.json，可以改成.conf

**Comment by garyelephant** [comment]
@cloudcba 如果没有其他问题，issue 就先close了。
