### ISSUE TITLE
Hive To Clickhouse 提示找不到类

### ISSUE THREAD

**Issue by sunhailin-Leo** [InterestingLab/waterdrop#599]
**Waterdrop Version(Waterdrop版本)**

`waterdrop-dist-2.0.4-2.11.8`

**Flink or Spark Version(Flink 或者 Spark 版本)**

`Spark 2.3.2.3.1.4.0-315`

**Java or Scala Version(Java或者Scala版本)**

`Using Scala version 2.11.12, Java HotSpot(TM) 64-Bit Server VM, 1.8.0_172`

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {}
input {}
filter {}
output {}
```

**Running Command(启动命令)**

`./bin/start-waterdrop-spark.sh --master yarn --deploy-mode cluster --config ./config/hive_2_clickhouse.conf`

**Error Exception**
```java
java.lang.ClassNotFoundException: io.github.interestinglab.waterdrop.spark.source.hive
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.github.interestinglab.waterdrop.config.ConfigBuilder.lambda$createPlugins$0(ConfigBuilder.java:147)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at io.github.interestinglab.waterdrop.config.ConfigBuilder.createPlugins(ConfigBuilder.java:144)
        at io.github.interestinglab.waterdrop.Waterdrop.entryPoint(Waterdrop.java:83)
        at io.github.interestinglab.waterdrop.Waterdrop.run(Waterdrop.java:50)
        at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:904)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Screenshots**
![image](https://user-images.githubusercontent.com/17564655/103739249-5171d900-5030-11eb-88fa-abcfc2032180.png)

**Comment by RickyHuo** [comment]
@sunhailin-Leo  https://github.com/InterestingLab/waterdrop/releases/tag/v1.5.1 请使用1.5.1

**Comment by sunhailin-Leo** [comment]
@RickyHuo 为啥 2.X 用不了？

**Comment by RickyHuo** [comment]
@sunhailin-Leo 2.x 支持的插件较少， 且以Flink为主， 如果只使用Spark 的话建议使用1.5
