### ISSUE TITLE
use waterdrop error

### ISSUE THREAD

**Issue by 279zlj** [InterestingLab/waterdrop#601]
spark2.3.1 use ./start-waterdrop.sh --config ../config/batch.conf --master yarn --deploy-mode client
error:
MoTTY X11 proxy: Unsupported authorisation protocol
Exception in thread "main" scala.MatchError: java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable. (of class java.awt.AWTError)
        at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:41)
        at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:904)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
why?

**Comment by garyelephant** [comment]
@279zlj 你好，请按照提ISSUE的格式要求把Context描述完整，方便帮你查问题。

**Comment by garyelephant** [comment]
@279zlj close this issue for no response for over 7+ days
