### ISSUE TITLE
how to set jvm config

### ISSUE THREAD

**Issue by lphcreat** [InterestingLab/waterdrop#604]
**Waterdrop Version(Waterdrop版本)**
1.5.1 

**Flink or Spark Version(Flink 或者 Spark 版本)**

spark 2.4

**Java or Scala Version(Java或者Scala版本)**

1.8

**question**
运行任务的时候怎么携带jvm参数呢？

**Comment by lphcreat** [comment]
找到了，./bin/start-waterdrop.sh --config ./config/demo.conf -e client -m 'local[2]' -i -Djava.awt.headless=false。但是我运行的时候还是提示安装X11.
21/02/01 11:02:59 INFO RetryingMetaStoreClient: RetryingMetaStoreClient proxy=class org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient ugi=root (auth:SIMPLE) retries=1 delay=5 lifetime=0
21/02/01 11:02:59 INFO Hive: Registering function encrypt_name com.byx.reallynameudf.ReallyNameUdf
Exception in thread "main" scala.MatchError: java.awt.AWTError: Can't connect to X11 window server using 'localhost:11.0' as the value of the DISPLAY variable. (of class java.awt.AWTError)
	at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:41)
	at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:904)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
21/02/01 11:03:18 INFO SparkContext: Invoking stop() from shutdown hook
