### ISSUE TITLE
spark-submit yarn cluster throws exception

### ISSUE THREAD

**Issue by long2chen** [InterestingLab/waterdrop#607]
**Waterdrop Version(Waterdrop版本)**
1.5.1
A clear version of Waterdrop. 

**Flink or Spark Version(Flink 或者 Spark 版本)**
spark-2.4.5

A clear version of Flink or Spark.

**Java or Scala Version(Java或者Scala版本)**
java version "1.8.0_231"

A clear version of Java or Scala.

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {
  # Waterdrop defined streaming batch duration in seconds
  spark.streaming.batchDuration = 5

  spark.app.name = "Waterdrop"
  spark.ui.port = 13000
}
input {
  jdbc {
    driver = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://xxxxxx:3306/xxx"
    table = "audit_log"
    result_table_name = "audit_log"
    user = "xxx"
    password = "xxx"
  }
}
filter {}
output {
 stdout {}
}
```

**Running Command(启动命令)**
./bin/start-waterdrop.sh --master yarn --deploy-mode cluster --config ./config/xxx.conf
请在这里添加完整的waterdrop启动命令及其参数。

**Error Exception**
Add exception about the problem here.(您可以将程序报错信息粘贴在此处)

Exception in thread "main" java.lang.NoSuchMethodError: org.elasticsearch.hadoop.cfg.Settings.getSecurityAuthenticationMethod()Lorg/elasticsearch/hadoop/security/AuthenticationMethod;
	at org.elasticsearch.spark.deploy.yarn.security.EsServiceCredentialProvider.credentialsRequired(EsServiceCredentialProvider.scala:104)
	at org.elasticsearch.spark.deploy.yarn.security.EsServiceCredentialProvider.credentialsRequired(EsServiceCredentialProvider.scala:84)
	at org.apache.spark.deploy.yarn.security.YARNHadoopDelegationTokenManager$$anonfun$obtainDelegationTokens$2.apply(YARNHadoopDelegationTokenManager.scala:62)
	at org.apache.spark.deploy.yarn.security.YARNHadoopDelegationTokenManager$$anonfun$obtainDelegationTokens$2.apply(YARNHadoopDelegationTokenManager.scala:61)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.apache.spark.deploy.yarn.security.YARNHadoopDelegationTokenManager.obtainDelegationTokens(YARNHadoopDelegationTokenManager.scala:61)
	at org.apache.spark.deploy.yarn.Client.setupSecurityToken(Client.scala:310)
	at org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:1014)
	at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:179)
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1135)
	at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1527)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by RickyHuo** [comment]
1.4.0 @long2chen  辛苦验证一下这个版本

**Comment by long2chen** [comment]
> 1.4.0 @long2chen 辛苦验证一下这个版本

**Comment by long2chen** [comment]
> 1.4.0 @long2chen 辛苦验证一下这个版本

1.4.0版本是可以的
