### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class

### ISSUE THREAD

**Issue by yanghuijava** [InterestingLab/waterdrop#636]
使用的waterdrop版本1.5.1

Spark 版本3.0.0

java版本：OpenJDK-1.8.0_252，Scala版本：2.12.10

配置信息

```
spark {
    spark.streaming.batchDuration = 5
    spark.app.name = "Waterdrop"
    spark.ui.port = 13000
}
input {
   socketStream {}
}
filter {
   split {
    fields = ["msg", "name"]
    delimiter = ","
  }
}
output {
  stdout {}
}
```
启动命令

请在这里添加完整的waterdrop启动命令及其参数。
```
./bin/start-waterdrop.sh --master local[4] --deploy-mode client --config ./config/application.conf
```
错误信息：
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class
        at io.github.interestinglab.waterdrop.Waterdrop$.<init>(Waterdrop.scala:21)
        at io.github.interestinglab.waterdrop.Waterdrop$.<clinit>(Waterdrop.scala)
        at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.internal.Logging$class
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 15 more

**Comment by RickyHuo** [comment]
请选择 spark2.x 基于scala 2.11 编译版本
