### ISSUE TITLE
Lorg/apache/spark/sql/expressions/UserDefinedFunction

### ISSUE THREAD

**Issue by 15850507548** [InterestingLab/waterdrop#649]
find and register UDFs & UDAFs
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.UDFRegistration.register(Ljava/lang/String;Lorg/apache/spark/sql/expressions/UserDefinedFunction;)Lorg/apache/spark/sql/expressions/UserDefinedFunction;
	at io.github.interestinglab.waterdrop.filter.UdfRegister$$anonfun$findAndRegisterUdfs$1$$anonfun$apply$1.apply(UdfRegister.scala:26)
	at io.github.interestinglab.waterdrop.filter.UdfRegister$$anonfun$findAndRegisterUdfs$1$$anonfun$apply$1.apply(UdfRegister.scala:24)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.github.interestinglab.waterdrop.filter.UdfRegister$$anonfun$findAndRegisterUdfs$1.apply(UdfRegister.scala:24)
	at io.github.interestinglab.waterdrop.filter.UdfRegister$$anonfun$findAndRegisterUdfs$1.apply(UdfRegister.scala:21)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.github.interestinglab.waterdrop.filter.UdfRegister$.findAndRegisterUdfs(UdfRegister.scala:21)
	at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:108)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:38)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:38)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:38)
	at scala.util.Try$.apply(Try.scala:192)
	at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:38)
	at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by garyelephant** [comment]
@15850507548 你好，仅靠此错误日志无法判断问题所在，请按照ISSUE模版提供程序启动的环境信息。

**Comment by RickyHuo** [comment]
使用Spark 2.4 或者 使用Waterdrop 1.4.x
