### ISSUE TITLE
尝试使用 clickhouse-jdbc.jar 从 clickhouse 同步到 hive 表

### ISSUE THREAD

**Issue by sunhailin-Leo** [InterestingLab/waterdrop#653]
**Waterdrop Version(Waterdrop版本)**

1.5.1

**Flink or Spark Version(Flink 或者 Spark 版本)**

Spark 2.3.2

**Java or Scala Version(Java或者Scala版本)**

jdk 1.8

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {
        spark.app.name = "aigroup_clickhouse_sync_to_hive_test"
        spark.executor.instances = 6
        spark.executor.cores = 6
        spark.executor.memory = "12g"
        spark.sql.catalogImplementation = "hive"
        spark.hadoop.hive.exec.dynamic.partition = "true"
        spark.hadoop.hive.exec.dynamic.partition.mode = "nonstrict"
}

input {
        jdbc {
               driver = "ru.yandex.clickhouse.ClickHouseDriver"
               url = "jdbc:clickhouse://****:****/ck_db_1"
               table = "basic_data"
               result_table_name = "basic_data_tmp"
               user = "root"
               password = "*****"
               jdbc.partitionColumn = "dt"
               jdbc.numPartitions = "10"
               jdbc.lowerBound = 0
               jdbc.upperBound = 100
        }
}

filter {
        sql {
                sql = "INSERT INTO t_1.basic_data PARTITION(dt) SELECT * FROM basic_data_tmp WHERE dt = '20210907'"
        }
}

output {
        stdout {
                limit = "10"
        }
}
```

**Running Command(启动命令)**

`/data/waterdrop/waterdrop-1.5.1/bin/start-waterdrop.sh --master yarn --deploy-mode client --queue pyspark --config /data/waterdrop/waterdrop-1.5.1/config/ck-to-hive.config`

**Error Exception**
```
21/09/09 21:10:59 WARN ThrowableSerializationWrapper: Task exception could not be deserialized
java.io.InvalidClassException: ru.yandex.clickhouse.except.ClickHouseException; local class incompatible: stream classdesc serialVersionUID = -3858489994429014405, local class serialVersionUID = -6984213296245514656
        at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:687)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1883)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1749)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2040)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at org.apache.spark.ThrowableSerializationWrapper.readObject(TaskEndReason.scala:193)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2176)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2067)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2285)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2209)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2067)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2285)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2209)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2067)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
        at org.apache.spark.scheduler.TaskResultGetter$$anon$4$$anonfun$run$2.apply$mcV$sp(TaskResultGetter.scala:136)
        at org.apache.spark.scheduler.TaskResultGetter$$anon$4$$anonfun$run$2.apply(TaskResultGetter.scala:132)
        at org.apache.spark.scheduler.TaskResultGetter$$anon$4$$anonfun$run$2.apply(TaskResultGetter.scala:132)
        at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1992)
        at org.apache.spark.scheduler.TaskResultGetter$$anon$4.run(TaskResultGetter.scala:132)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
21/09/09 21:10:59 WARN TaskSetManager: Lost task 4.0 in stage 0.0 (TID 4, hdp065-pro.idc.jtexpress.com.cn, executor 4): UnknownReason
21/09/09 21:10:59 INFO TaskSetManager: Starting task 4.1 in stage 0.0 (TID 10, IPDTHDP08050108, executor 5, partition 4, PROCESS_LOCAL, 7711 bytes)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/17564655/132693065-09ea94a1-c1ff-48f9-90c0-46b38ae33e82.png)

**Comment by sunhailin-Leo** [comment]
* 扩展的 plugins 从 https://github.com/ClickHouse/clickhouse-jdbc/releases/tag/v0.3.1-patch 来的
![image](https://user-images.githubusercontent.com/17564655/132693325-3919fad1-228b-4095-a5c1-f82b29353dd8.png)

**Comment by sunhailin-Leo** [comment]
* 我发现用 plugins 的方式加载不行，会出现上面这个问题。后面我在任务 config 文件指定 spark 的配置中加了这两个`spark.executor.extraClassPath` 和 `spark.driver.extraClassPath`就好了

**Comment by sunhailin-Leo** [comment]
* 给 clickhouse-jdbc 库的提了个 issue 关于序列化ID 的问题：https://github.com/ClickHouse/clickhouse-jdbc/issues/718

**Comment by sunhailin-Leo** [comment]
* 最后的配置是这样的
```
spark {
        spark.app.name = "aigroup_clickhouse_sync_to_hive_test"
        spark.executor.instances = 6
        spark.executor.cores = 6
        spark.executor.memory = "12g"
        spark.sql.catalogImplementation = "hive"
        spark.hadoop.hive.exec.dynamic.partition = "true"
        spark.hadoop.hive.exec.dynamic.partition.mode = "nonstrict"
        spark.driver.extraClassPath = "/data/waterdrop/waterdrop-1.5.1/plugins/my_plugins/lib/clickhouse-jdbc-0.3.1-patch.jar"
        spark.executor.extraClassPath = "clickhouse-jdbc-0.3.1-patch.jar"
}

input {
        jdbc {
               driver = "ru.yandex.clickhouse.ClickHouseDriver"
               url = "jdbc:clickhouse://*****:*****/ai_group"
               table = "basic_data"
               result_table_name = "basic_data_tmp"
               user = "root"
               password = "*****"
        }
}

filter {
        sql {
                sql = "INSERT INTO t_1.basic_data PARTITION(dt) SELECT * FROM basic_data_tmp WHERE dt = '20210907'"
        }
}

output {
        stdout {
                limit = "10"
        }
}
```

* 踩坑点，如果 `clickhouse` 里面分区的列类型不属于 numeric, date, or timestamp 这几种的话，无法使用分区方式拉取数据
```
jdbc.partitionColumn = "dt"
jdbc.numPartitions = "10"
jdbc.lowerBound = 0
jdbc.upperBound = 100
```

**Comment by RickyHuo** [comment]
@sunhailin-Leo  因为waterdrop项目里面已经有clickhouse-jdbc， 所以不需要额外在plugins里面添加 jar
